import type { KnowledgeCard, KnowledgeTopicPack } from "./types.js";
import { defineCard } from "./types.js";

export const activeDirectoryTopicId = "active-directory" as const;
export const activeDirectoryDisplayName = "Active Directory";

export const activeDirectoryKnowledgeCards: KnowledgeCard[] = [
  defineCard("active-directory", "Active Directory", ["active directory", "актив директори", "что такое active directory", "ad domain"], "active-directory", "Каталог Microsoft для централизованного управления пользователями, компьютерами, группами и политиками домена.", ["Основной протокол каталога — LDAP, аутентификация обычно использует Kerberos.", "Структура включает forest, domain и organizational units.", "AD сильно зависит от корректного DNS."], ["Get-ADDomain", "Get-ADUser -Filter *"], ["domain-controller", "group-policy", "active-directory-dns"]),
  defineCard("domain-controller", "Domain Controller", ["domain controller", "контроллер домена", "что такое domain controller", "dc active directory"], "active-directory", "Сервер с ролью AD DS, который аутентифицирует пользователей и хранит реплицируемую копию каталога.", ["Обычно также участвует в DNS домена.", "Несколько DC повышают отказоустойчивость.", "FSMO-роли распределяют отдельные обязанности."], ["Get-ADDomainController -Filter *", "dcdiag"], ["active-directory", "active-directory-dns", "kerberos"]),
  defineCard("group-policy", "Group Policy", ["group policy", "групповая политика", "gpo", "что такое group policy"], "active-directory", "Механизм централизованной настройки пользователей и компьютеров Windows в домене.", ["Настройки хранятся в GPO и связываются с site, domain или OU.", "Порядок и наследование влияют на итоговую политику."], ["gpupdate /force", "gpresult /r", "Get-GPO -All"], ["active-directory", "organizational unit"]),
  defineCard("active-directory-dns", "DNS в Active Directory", ["dns in ad", "dns в active directory", "ad dns", "dns active directory"], "active-directory", "DNS помогает клиентам находить контроллеры домена и службы AD через специальные SRV-записи.", ["Клиенты домена должны использовать DNS, знающий зону AD.", "Ошибочный внешний DNS часто ломает domain join и вход.", "AD-integrated зоны могут реплицироваться через каталог."], ["nslookup -type=SRV _ldap._tcp.dc._msdcs.DOMAIN", "dcdiag /test:dns"], ["active-directory", "domain-controller", "dns"]),
  defineCard("dhcp-role", "DHCP role", ["dhcp role", "роль dhcp", "dhcp server windows", "dhcp в windows server"], "active-directory", "Серверная роль, которая централизованно выдает IP-конфигурацию клиентам сети.", ["Scope определяет пул адресов и параметры сети.", "В доменной среде DHCP-сервер обычно авторизуют в AD.", "Failover помогает обеспечить доступность выдачи адресов."], ["Get-DhcpServerv4Scope", "Get-DhcpServerInDC"], ["dhcp", "active-directory", "dns"]),
  defineCard("ad-check-domain-controller", "Проверка контроллеров домена", ["проверить контроллер домена", "check domain controller", "list domain controllers", "get addomaincontroller"], "active-directory", "Показывает доступные Domain Controller и помогает проверить, какой DC обслуживает клиент.", ["Проверяйте DNS, site и доступность нужного DC.", "Переменная LOGONSERVER показывает DC текущего входа."], ["echo %LOGONSERVER%", "nltest /dsgetdc:DOMAIN", "Get-ADDomainController -Filter *"], ["domain controller", "dns in ad", "dcdiag"]),
  defineCard("ad-dns-records", "Проверка DNS-записей Active Directory", ["проверить dns записи ad", "check ad dns records", "ad srv records", "dns records active directory"], "active-directory", "Проверяет SRV-записи, по которым клиенты находят LDAP, Kerberos и контроллеры домена.", ["Клиент домена должен использовать внутренний DNS AD.", "Отсутствующие SRV-записи часто указывают на проблемы DNS или Netlogon."], ["nslookup -type=SRV _ldap._tcp.dc._msdcs.DOMAIN", "Resolve-DnsName -Type SRV _kerberos._tcp.DOMAIN", "dcdiag /test:dns"], ["dns in ad", "domain controller", "dcdiag"]),
  defineCard("ad-gpupdate", "Обновление групповых политик: gpupdate", ["gpupdate", "gpupdate force", "обновить групповые политики", "refresh group policy"], "active-directory", "Принудительно обновляет пользовательские и компьютерные Group Policy на Windows-клиенте.", ["/force повторно применяет все параметры.", "Некоторые политики требуют выхода пользователя или перезагрузки."], ["gpupdate /force", "gpupdate /target:computer /force"], ["group policy", "gpresult", "gpo"]),
  defineCard("ad-gpresult", "Проверка примененных политик: gpresult", ["gpresult", "gpresult command", "какие gpo применились", "check applied group policy", "resultant set of policy"], "active-directory", "Показывает примененные GPO и итоговые параметры для пользователя или компьютера.", ["/r дает краткий отчет.", "/h создает удобный HTML-отчет для анализа."], ["gpresult /r", "gpresult /h C:\\Temp\\gpresult.html"], ["group policy", "gpupdate", "gpo"]),
  defineCard("ad-dcdiag", "Диагностика контроллера домена: dcdiag", ["dcdiag", "dcdiag command", "dcdiag проверить контроллер домена", "диагностика контроллера домена", "test domain controller health"], "active-directory", "Запускает набор проверок состояния AD DS, DNS, репликации и служб Domain Controller.", ["Запускайте от администратора на DC или с подходящими RSAT.", "Ошибку лучше проверять вместе с Event Viewer и repadmin."], ["dcdiag", "dcdiag /v", "dcdiag /test:dns"], ["domain controller", "repadmin", "dns in ad"]),
  defineCard("ad-repadmin", "Проверка репликации AD: repadmin", ["repadmin", "repadmin command", "проверить репликацию ad", "active directory replication status"], "active-directory", "Показывает состояние репликации между контроллерами домена и последние ошибки.", ["/replsummary дает сводку по всем DC.", "/showrepl показывает входящие партнеры выбранного DC."], ["repadmin /replsummary", "repadmin /showrepl", "repadmin /syncall /AdeP"], ["domain controller", "dcdiag", "replication"]),
  defineCard("ad-fsmo", "Проверка FSMO-ролей", ["fsmo roles", "как проверить fsmo", "проверить fsmo", "проверить fsmo роли", "check fsmo roles", "netdom query fsmo"], "active-directory", "Показывает, какие Domain Controller владеют пятью специальными FSMO-ролями леса и домена.", ["Роли включают Schema Master, Domain Naming Master, RID, PDC Emulator и Infrastructure Master.", "Знать владельцев важно при обслуживании или отказе DC."], ["netdom query fsmo", "Get-ADForest | Select SchemaMaster,DomainNamingMaster", "Get-ADDomain | Select RIDMaster,PDCEmulator,InfrastructureMaster"], ["domain controller", "active directory", "replication"]),
  defineCard("ad-gpo-basics", "Основы GPO", ["gpo basics", "основы gpo", "как работает групповая политика", "group policy basics"], "active-directory", "GPO централизованно применяет настройки к пользователям и компьютерам в site, domain и OU.", ["Порядок обработки обычно LSDOU: Local, Site, Domain, OU.", "Security filtering и WMI filters ограничивают область применения."], ["Get-GPO -All", "gpresult /h C:\\Temp\\gpresult.html", "rsop.msc"], ["group policy", "gpupdate", "gpresult"]),
  defineCard("windows-whoami-groups", "Группы текущего пользователя: whoami /groups", ["whoami /groups", "группы пользователя windows", "user group membership windows", "в каких группах пользователь"], "active-directory", "Показывает группы и SID, включенные в текущий Windows access token.", ["После изменения membership может потребоваться новый вход.", "Deny-only и disabled SID важны при анализе реальных прав."], ["whoami /groups", "whoami /all"], ["ad groups", "token", "permissions"]),
  defineCard("windows-flush-dns", "Очистка DNS-кеша Windows", ["ipconfig /flushdns", "flush dns cache", "очистить dns кеш", "сбросить dns windows"], "active-directory", "Удаляет локально закешированные DNS-ответы клиента Windows.", ["Полезно после изменения записи или исправления resolver.", "Команда не исправляет неправильную запись на DNS-сервере."], ["ipconfig /displaydns", "ipconfig /flushdns", "Resolve-DnsName HOST"], ["dns", "cache", "windows"]),
  defineCard("windows-secure-channel", "Проверка secure channel компьютера", ["test-computersecurechannel", "check secure channel", "проверить secure channel", "сломано доверие домена", "trust relationship failed"], "active-directory", "Проверяет доверительный канал между domain member и Active Directory domain.", ["False указывает на проблему machine account, DNS, времени или связи с DC.", "Ремонт выполняйте только после проверки DNS и доступности контроллера."], ["Test-ComputerSecureChannel -Verbose", "Test-ComputerSecureChannel -Repair -Credential DOMAIN\\Admin", "nltest /sc_verify:DOMAIN"], ["domain", "computer account", "domain controller"]),
  defineCard("ad-groups", "Группы Active Directory", ["ad groups", "группы active directory", "проверить группы ad", "get-adgroup", "group membership ad"], "active-directory", "AD groups объединяют пользователей, компьютеры и другие группы для назначения доступа.", ["Security groups используются в ACL, distribution groups — для почты.", "Scope Domain Local, Global и Universal влияет на допустимое membership и область использования."], ["Get-ADGroup -Filter *", "Get-ADPrincipalGroupMembership USER", "Get-ADGroupMember GROUP"], ["permissions", "users", "nested groups"]),
  defineCard("active-directory-create-user", "Создание пользователя в Active Directory", ["как добавить пользователя в active directory", "как создать пользователя в active directory", "добавить пользователя в active directory", "создать пользователя в active directory", "как добавить пользователя в ad", "как создать пользователя в ad", "создание пользователя ad", "new-aduser", "добавить пользователя в актив директори", "создать пользователя в актив директори"], "active-directory", "Учетную запись AD можно создать в нужном OU через Active Directory Users and Computers или PowerShell-командой New-ADUser.", ["В ADUC откройте нужный OU, выберите New -> User и заполните имя, фамилию и logon name.", "Задайте начальный пароль и параметры его смены, затем проверьте OU и членство в группах.", "Проверьте уникальность SamAccountName и UPN; не храните открытый пароль в скриптах."], ["New-ADUser `\n  -Name \"Ivan Petrov\" `\n  -GivenName \"Ivan\" `\n  -Surname \"Petrov\" `\n  -SamAccountName \"i.petrov\" `\n  -UserPrincipalName \"i.petrov@example.local\" `\n  -Path \"OU=Users,DC=example,DC=local\" `\n  -Enabled $true `\n  -AccountPassword (Read-Host -AsSecureString \"Password\")", "Set-ADAccountPassword -Identity USER -Reset -NewPassword (Read-Host -AsSecureString)", "Enable-ADAccount -Identity USER", "Add-ADGroupMember -Identity GROUP -Members USER"], ["active directory", "users", "aduc", "new-aduser", "organizational unit", "powershell"]),
  defineCard("active-directory-add-user-to-group", "Добавление пользователя в группу Active Directory", ["как добавить пользователя в группу active directory", "добавить пользователя в группу active directory", "как добавить пользователя в группу ad", "добавить пользователя в группу ad", "add-adgroupmember"], "active-directory", "Добавляет существующую учетную запись AD в нужную группу через ADUC или PowerShell.", ["В ADUC откройте свойства группы или пользователя и измените membership.", "Перед добавлением проверьте назначение и scope группы.", "После изменения членства пользователю может потребоваться новый вход для обновления access token."], ["Add-ADGroupMember -Identity GROUP -Members USER", "Get-ADGroupMember -Identity GROUP", "Get-ADPrincipalGroupMembership -Identity USER"], ["active directory", "users", "groups", "membership", "powershell"]),
  defineCard("ad-user-lookup", "Поиск пользователя Active Directory", ["как проверить пользователя ad", "проверить пользователя ad", "как проверить пользователя active directory", "проверить пользователя active directory", "как найти пользователя active directory", "найти пользователя active directory", "get-aduser identity", "get-aduser filter"], "active-directory", "Находит учетную запись пользователя в Active Directory и показывает ее основные свойства.", ["Для точного login используйте -Identity.", "Для поиска по имени применяйте -Filter; в графическом ADUC можно использовать поиск по домену или OU."], ["Get-ADUser -Identity username", "Get-ADUser -Filter 'Name -like \"*Ivan*\"'"], ["active directory", "users", "aduc", "powershell"]),
  defineCard("ad-nested-groups", "Вложенные группы Active Directory", ["nested groups", "вложенные группы ad", "группа в группе active directory", "recursive group membership"], "active-directory", "Вложенные группы упрощают модель ролей, но могут скрывать источник эффективного доступа.", ["Для рекурсивного membership используйте специальный LDAP matching rule или PowerShell.", "Изменения token membership требуют нового входа пользователя."], ["Get-ADGroupMember GROUP -Recursive", "Get-ADPrincipalGroupMembership USER"], ["ad groups", "permissions", "token"]),
  defineCard("ad-sysvol", "Основы SYSVOL", ["sysvol basics", "что такое sysvol", "sysvol active directory", "проверить sysvol"], "active-directory", "SYSVOL хранит общие части GPO и logon scripts, реплицируемые между Domain Controllers.", ["Каталог публикуется через сетевые shares SYSVOL и NETLOGON.", "Проблемы DFSR могут приводить к разным версиям GPO на DC."], ["net share", "dcdiag /test:sysvolcheck", "dfsrdiag ReplicationState"], ["gpo", "dfsr", "domain controller"]),
  defineCard("windows-dns-role", "Основы DNS Server в Windows", ["windows dns role", "dns role basics", "роль dns windows server", "проверить dns server windows"], "active-directory", "Windows DNS Server обслуживает zones и часто хранит AD-integrated зоны домена.", ["Проверьте состояние службы DNS, зоны и forwarders.", "Для AD критичны SRV-записи и использование внутреннего DNS клиентами."], ["Get-Service DNS", "Get-DnsServerZone", "Get-DnsServerForwarder", "dcdiag /test:dns"], ["dns", "active directory", "srv records"]),
  defineCard("windows-event-viewer", "Основы Event Viewer", ["event viewer basics", "просмотр событий windows", "логи windows", "как посмотреть события windows", "get-winevent"], "active-directory", "Event Viewer хранит системные, security и application события Windows.", ["Фильтруйте по времени, level, source и Event ID.", "Для автоматизации используйте Get-WinEvent."], ["eventvwr.msc", "Get-WinEvent -LogName System -MaxEvents 50", "Get-WinEvent -FilterHashtable @{LogName='System'; Level=2}"], ["windows", "logs", "event id"]),
  defineCard("windows-service-status", "Статус Windows service", ["windows service status", "проверить службу windows", "get-service", "powershell get-service", "статус сервиса windows"], "active-directory", "Показывает состояние Windows services и тип запуска.", ["Get-Service удобен для статуса, Get-CimInstance дает дополнительные свойства.", "Проверьте зависимые службы и Event Viewer при ошибке запуска."], ["Get-Service -Name SERVICE", "sc.exe query SERVICE", "Get-CimInstance Win32_Service -Filter \"Name='SERVICE'\""], ["windows service", "powershell", "event viewer"]),
  defineCard("windows-service-restart", "Перезапуск Windows service", ["restart windows service", "перезапустить службу windows", "restart-service", "powershell restart-service"], "active-directory", "Останавливает и повторно запускает выбранную Windows service.", ["Команда требует соответствующих прав.", "При зависании stop проверьте PID и причину в Event Viewer."], ["Restart-Service -Name SERVICE", "Restart-Service -Name SERVICE -Force", "sc.exe stop SERVICE && sc.exe start SERVICE"], ["windows service", "powershell", "status"]),
  defineCard("windows-test-netconnection", "Проверка сети: Test-NetConnection", ["test-netconnection", "powershell test-netconnection", "проверить порт powershell", "test tcp port windows"], "active-directory", "PowerShell-команда проверяет DNS, ICMP, route и TCP port в Windows.", ["TcpTestSucceeded — ключевой результат проверки порта.", "-DiagnoseRouting помогает увидеть выбранный route и source address."], ["Test-NetConnection HOST -Port 443", "Test-NetConnection HOST -TraceRoute", "Test-NetConnection HOST -DiagnoseRouting"], ["tcp", "port", "powershell"]),
  defineCard(
    "active-directory-samba-ad-dc-overview",
    "Samba Active Directory Domain Controller",
    [
      "что такое samba ad dc", "samba контроллер домена", "samba active directory", "samba domain controller",
      "samba ad", "контроллер домена на linux", "заменить windows ad на samba", "samba tool",
      "как проверить репликацию samba ad", "репликация samba ad"
    ],
    "active-directory",
    "Samba AD DC предоставляет совместимые с Active Directory службы контроллера домена: LDAP, Kerberos, DNS-интеграцию, SYSVOL и поддержку групповых политик.",
    [
      "Это отдельная роль, отличная от классического standalone Samba file server; не совмещайте и не преобразуйте production-роли без плана.",
      "Миграция существующего Windows AD требует проверки DNS, синхронизации времени, репликации, FSMO и SYSVOL.",
      "Перед изменениями проверяйте состояние домена и репликации и планируйте откат."
    ],
    [
      "samba-tool domain info DOMAIN", "samba-tool drs showrepl", "samba-tool fsmo show",
      "samba-tool user list", "samba-tool group list", "samba-tool dbcheck"
    ],
    ["samba ad", "domain controller", "ldap", "kerberos", "dns", "sysvol", "gpo", "replication"]
  ),
];

export const activeDirectoryTopicPack: KnowledgeTopicPack = {
  id: activeDirectoryTopicId,
  displayName: activeDirectoryDisplayName,
  cards: activeDirectoryKnowledgeCards
};
