import type { KnowledgeCard, KnowledgeTopicPack } from "./types.js";
import { defineCard } from "./types.js";

export const dockerTopicId = "docker" as const;
export const dockerDisplayName = "Docker";

export const dockerKnowledgeCards: KnowledgeCard[] = [
  defineCard("docker-image", "Docker image", ["docker image", "образ docker", "docker образ", "что такое docker image"], "docker", "Неизменяемый шаблон с приложением, зависимостями и метаданными для запуска контейнеров.", ["Image строится слоями.", "Один image может запускать много контейнеров.", "Обычно хранится в registry."], ["docker image ls", "docker inspect IMAGE"], ["docker-container", "dockerfile", "registry"]),
  defineCard("docker-container", "Docker container", ["docker container", "контейнер docker", "docker контейнер", "что такое контейнер"], "docker", "Запущенный или остановленный экземпляр Docker image с изолированными процессами и файловой системой.", ["Контейнер не является полноценной виртуальной машиной.", "Изменяемые данные лучше хранить в volume."], ["docker ps -a", "docker inspect CONTAINER"], ["docker-image", "docker-run", "volume"]),
  defineCard("docker-overview", "Docker: основные компоненты", ["что такое docker", "из чего состоит docker", "основные компоненты docker", "расскажи про docker", "для чего нужен docker"], "docker", "Docker — платформа для сборки, доставки и запуска приложений в контейнерах.", ["Dockerfile описывает сборку image.", "Image хранит неизменяемый шаблон приложения, container является его запущенным экземпляром.", "Docker Engine управляет контейнерами, registry хранит images, volumes и networks отвечают за данные и сеть."], ["docker version", "docker info", "docker ps", "docker image ls"], ["dockerfile", "image", "container", "registry", "volume", "network"]),
  defineCard("dockerfile", "Dockerfile", ["dockerfile", "docker file", "docker-файл", "докер файл", "докер-файл", "докерфайл", "что такое dockerfile", "что такое docker файл", "что такое docker-файл", "что такое докер файл", "что такое докер-файл", "из чего состоит dockerfile", "из чего состоит docker файл", "из чего состоит docker-файл", "из чего состоит докер файл", "из чего состоит докер-файл", "что в dockerfile", "что в docker-файле", "что пишут в dockerfile", "что вы знаете про dockerfile", "структура dockerfile", "инструкции dockerfile", "from run copy cmd entrypoint", "что стоит docker файл", "что стоит docker-файл", "что состоит docker файл", "что состоит docker-файл", "из чего dockerfile"], "docker", "Dockerfile — текстовый рецепт сборки Docker image из последовательности инструкций.", ["FROM задает базовый image; RUN выполняет команды сборки.", "COPY и ADD добавляют файлы, WORKDIR задает рабочий каталог, ENV — переменные окружения, EXPOSE документирует порт.", "CMD и ENTRYPOINT определяют команду запуска контейнера.", "Инструкции сборки могут создавать отдельные слои image, поэтому их порядок влияет на кеш и размер."], ["docker build -t my-app ."], ["docker-image", "docker-build", "FROM", "RUN", "COPY", "ADD", "WORKDIR", "ENV", "EXPOSE", "CMD", "ENTRYPOINT"]),
  defineCard("docker-build", "docker build", ["docker build", "собрать docker image", "сборка docker образа"], "docker", "Собирает Docker image по Dockerfile и build context.", ["Контекст обычно указывается последним аргументом.", "Тег -t делает image удобным для запуска и публикации."], ["docker build -t my-app:latest .", "docker build --no-cache -t my-app ."], ["dockerfile", "docker-image"]),
  defineCard("docker-run", "docker run", ["docker run", "запустить docker контейнер", "run container"], "docker", "Создает контейнер из image и запускает его.", ["-d запускает в фоне.", "-p публикует порт, -v подключает volume, --rm удаляет контейнер после остановки."], ["docker run --rm -p 8080:80 nginx", "docker run -d --name app my-app"], ["docker-container", "docker-image"]),
  defineCard("docker-ps", "docker ps", ["docker ps", "список docker контейнеров", "list docker containers"], "docker", "Показывает запущенные контейнеры и их состояние.", ["Без ключей видны только запущенные контейнеры.", "-a добавляет остановленные контейнеры."], ["docker ps", "docker ps -a", "docker ps --format \"table {{.Names}}\\t{{.Status}}\\t{{.Ports}}\""], ["docker-container", "docker-logs"]),
  defineCard("docker-logs", "docker logs", ["docker logs", "логи docker контейнера", "логи контейнера", "container logs", "как посмотреть логи docker", "показать логи docker"], "docker", "Показывает stdout и stderr выбранного контейнера.", ["-f продолжает следить за новыми строками.", "--since ограничивает временной диапазон."], ["docker logs CONTAINER", "docker logs -f --tail 100 CONTAINER"], ["docker-container", "journalctl"]),
  defineCard("docker-images", "Список Docker images", ["docker images", "docker image ls", "список docker образов", "показать docker images", "list docker images"], "docker", "Показывает локальные Docker images, их теги, ID, дату и размер.", ["Dangling images не имеют тега и часто остаются после сборок.", "Удаляйте image только когда он не нужен контейнерам."], ["docker images", "docker image ls", "docker image prune"], ["docker image", "docker build", "registry"]),
  defineCard("docker-exec", "Выполнение команды в контейнере: docker exec", ["docker exec", "как зайти в контейнер", "зайти в контейнер", "зайти в docker контейнер", "выполнить команду в контейнере", "shell in container", "execute in docker container"], "docker", "Запускает новый процесс внутри уже работающего контейнера.", ["-it нужен для интерактивного терминала.", "В минимальных images может быть sh, но не bash."], ["docker exec -it CONTAINER sh", "docker exec CONTAINER env"], ["docker container", "docker ps", "shell"]),
  defineCard("docker-inspect", "Подробности объекта: docker inspect", ["docker inspect", "посмотреть настройки контейнера", "inspect docker container", "docker container details"], "docker", "Возвращает подробную JSON-конфигурацию контейнера, image, volume или network.", ["Полезен для IP, mounts, environment и restart policy.", "--format позволяет извлечь одно поле."], ["docker inspect CONTAINER", "docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' CONTAINER"], ["docker container", "docker network", "docker volume"]),
  defineCard("docker-compose-up", "Запуск Compose-проекта: docker compose up", ["docker compose up", "запустить docker compose", "compose up", "start compose project"], "docker", "Создает и запускает сервисы, сети и volumes из compose.yaml.", ["-d запускает проект в фоне.", "--build пересобирает images перед запуском."], ["docker compose up -d", "docker compose up -d --build"], ["docker compose down", "compose", "docker service"]),
  defineCard("docker-compose-down", "Остановка Compose-проекта: docker compose down", ["docker compose down", "остановить docker compose", "compose down", "stop compose project"], "docker", "Останавливает и удаляет контейнеры и сети текущего Compose-проекта.", ["Volumes по умолчанию сохраняются.", "Ключ -v удаляет named volumes и данные в них."], ["docker compose down", "docker compose down -v"], ["docker compose up", "compose", "docker volume"]),
  defineCard("docker-compose-logs", "Логи Compose-сервисов: docker compose logs", ["docker compose logs", "логи docker compose", "посмотреть логи compose", "compose service logs", "follow compose logs"], "docker", "Собирает stdout и stderr сервисов Compose-проекта.", ["Укажите имя сервиса, чтобы сократить вывод.", "-f продолжает показывать новые строки."], ["docker compose logs", "docker compose logs -f --tail 100 SERVICE"], ["docker logs", "docker compose up", "logs"]),
  defineCard("docker-volumes", "Docker volumes", ["docker volumes", "docker volume", "тома docker", "что такое docker volume", "list docker volumes"], "docker", "Хранят данные контейнеров отдельно от их изменяемого слоя.", ["Named volume переживает пересоздание контейнера.", "Перед удалением проверьте, что данные больше не нужны."], ["docker volume ls", "docker volume inspect VOLUME", "docker volume prune"], ["docker container", "mount", "persistent data"]),
  defineCard("docker-networks", "Docker networks", ["docker networks", "docker network", "сети docker", "что такое docker network", "list docker networks"], "docker", "Соединяют контейнеры и обеспечивают DNS по именам контейнеров или сервисов.", ["Пользовательская bridge-сеть удобнее стандартной для связи контейнеров.", "inspect показывает подключенные контейнеры и подсети."], ["docker network ls", "docker network inspect NETWORK", "docker network create app-net"], ["docker container", "dns", "bridge"]),
  defineCard("docker-ps-all", "Все Docker-контейнеры: docker ps -a", ["docker ps -a", "all docker containers", "показать остановленные контейнеры", "все контейнеры docker"], "docker", "Показывает и запущенные, и остановленные контейнеры.", ["Столбец STATUS помогает увидеть exit code и время остановки.", "Для диагностики затем используйте docker logs и docker inspect."], ["docker ps -a", "docker ps -a --filter status=exited"], ["docker ps", "container", "troubleshooting"]),
  defineCard("docker-logs-follow", "Логи контейнера в реальном времени: docker logs -f", ["docker logs -f", "follow docker logs", "следить за логами контейнера", "как посмотреть логи контейнера", "логи контейнера онлайн"], "docker", "Подключается к stdout/stderr контейнера и продолжает показывать новые строки.", ["--tail ограничивает начальный объем вывода.", "Ctrl+C прекращает просмотр, но не останавливает контейнер."], ["docker logs -f --tail 100 CONTAINER", "docker logs --since 10m CONTAINER"], ["docker logs", "container", "logs"]),
  defineCard("docker-stats", "Ресурсы контейнеров: docker stats", ["docker stats", "docker container resources", "нагрузка контейнеров", "память cpu docker", "как посмотреть нагрузку docker"], "docker", "Показывает CPU, память, сеть и I/O работающих контейнеров.", ["Используйте --no-stream для одного снимка.", "Лимиты контейнера смотрите отдельно через inspect."], ["docker stats", "docker stats --no-stream", "docker inspect CONTAINER --format '{{json .HostConfig.Resources}}'"], ["container", "cpu", "memory"]),
  defineCard("docker-pull", "Загрузка image: docker pull", ["docker pull", "скачать docker image", "pull docker image", "обновить образ docker"], "docker", "Загружает image или конкретный tag из registry.", ["Без tag обычно используется latest, но это не гарантия самой новой версии.", "Для воспроизводимости фиксируйте версию или digest."], ["docker pull nginx:1.27", "docker pull IMAGE@sha256:DIGEST"], ["image", "registry", "tag"]),
  defineCard("docker-lifecycle", "Остановка и перезапуск контейнера", ["docker stop start restart", "docker restart", "перезапустить контейнер", "остановить контейнер", "запустить остановленный контейнер"], "docker", "Управляет жизненным циклом уже созданного контейнера.", ["stop посылает сигнал завершения и ждет timeout.", "restart удобен для быстрого перезапуска, но не меняет конфигурацию контейнера."], ["docker stop CONTAINER", "docker start CONTAINER", "docker restart CONTAINER"], ["container", "docker ps", "signals"]),
  defineCard("docker-remove", "Удаление контейнеров и images", ["docker rm rmi", "docker rm", "docker rmi", "удалить контейнер docker", "удалить образ docker"], "docker", "Удаляет остановленные контейнеры и неиспользуемые images.", ["Работающий контейнер сначала остановите.", "Перед массовой очисткой проверьте, какие объекты действительно не используются."], ["docker rm CONTAINER", "docker rmi IMAGE", "docker container prune", "docker image prune"], ["container", "image", "cleanup"]),
  defineCard("docker-volume-list", "Список Docker volumes", ["docker volume ls", "список docker volumes", "list docker volumes", "посмотреть тома docker"], "docker", "Показывает именованные volumes, хранящие постоянные данные контейнеров.", ["Dangling volumes не связаны с контейнерами, но могут содержать нужные данные.", "Не удаляйте volume без проверки владельца и содержимого."], ["docker volume ls", "docker volume ls -f dangling=true"], ["volume", "storage", "docker inspect"]),
  defineCard("docker-volume-inspect", "Проверка Docker volume", ["docker volume inspect", "inspect docker volume", "где хранится docker volume", "проверить том docker"], "docker", "Показывает driver, mountpoint, labels и параметры volume.", ["Mountpoint относится к Docker host.", "Для remote driver детали могут отличаться."], ["docker volume inspect VOLUME", "docker inspect CONTAINER --format '{{json .Mounts}}'"], ["volume", "mount", "storage"]),
  defineCard("docker-network-list", "Список Docker networks", ["docker network ls", "список docker networks", "list docker networks", "посмотреть сети docker"], "docker", "Показывает сети Docker и используемые network drivers.", ["bridge — типичная локальная сеть одного host.", "Compose обычно создает отдельную сеть проекта."], ["docker network ls", "docker network ls --filter driver=bridge"], ["network", "bridge", "compose"]),
  defineCard("docker-network-inspect", "Проверка Docker network", ["docker network inspect", "inspect docker network", "контейнеры в сети docker", "проверить сеть docker"], "docker", "Показывает subnet, gateway и подключенные к сети контейнеры.", ["Полезно при ошибках DNS и связи между контейнерами.", "Проверьте, что оба контейнера подключены к одной сети."], ["docker network inspect NETWORK", "docker inspect CONTAINER --format '{{json .NetworkSettings.Networks}}'"], ["network", "dns", "container"]),
  defineCard("docker-start-troubleshooting", "Контейнер не запускается: быстрая диагностика", ["container cannot start", "контейнер не стартует", "контейнер не запускается", "docker container exits", "docker контейнер сразу падает"], "docker", "Последовательно проверяет статус, exit code, логи и фактическую конфигурацию контейнера.", ["Exit code 0 может означать, что основной процесс просто завершился.", "Проверьте command, mounts, environment и доступность зависимостей."], ["docker ps -a", "docker logs --tail 200 CONTAINER", "docker inspect CONTAINER --format '{{.State.ExitCode}} {{.State.Error}}'", "docker start -a CONTAINER"], ["container", "logs", "inspect"]),
  defineCard("docker-port-mapping", "Публикация портов Docker", ["docker port mapping", "проброс портов docker", "docker -p", "порт контейнера", "как открыть порт контейнера"], "docker", "Связывает порт Docker host с портом приложения внутри контейнера.", ["Запись HOST_PORT:CONTAINER_PORT публикует TCP по умолчанию.", "Приложение внутри контейнера должно слушать нужный адрес и порт."], ["docker run -p 8080:80 nginx", "docker port CONTAINER", "docker ps --format 'table {{.Names}}\t{{.Ports}}'"], ["port", "container", "nat"]),
  defineCard("dockerfile-instructions", "Dockerfile: RUN, COPY, ADD, CMD и ENTRYPOINT", ["dockerfile run copy add cmd entrypoint", "dockerfile instructions", "разница cmd entrypoint", "copy или add dockerfile", "run в dockerfile"], "docker", "Основные инструкции Dockerfile формируют image и задают процесс контейнера.", ["RUN выполняется при сборке; CMD и ENTRYPOINT — при запуске.", "COPY предпочтительнее ADD, если не нужны специальные возможности ADD."], ["RUN apt-get update && apt-get install -y curl", "COPY . /app", "ENTRYPOINT [\"/app/server\"]", "CMD [\"--help\"]"], ["dockerfile", "image", "build"]),
  defineCard("docker-image-layers", "Слои Docker image", ["что такое слой docker", "что такое слой докера", "что такое слои докера", "как устроен слой докера", "из чего состоит слой докера", "как посмотреть слои докера", "слои образа докера", "слой docker-образа", "что такое docker layer", "что такое docker layers", "как устроен docker layer", "из чего состоит docker layer", "как посмотреть docker layers", "docker layer", "docker layers", "из чего состоит docker-образ", "из чего состоит docker образ", "как посмотреть слои docker", "docker image layers", "слои docker image", "как устроены слои docker", "docker history", "docker image history"], "docker", "Docker image состоит из неизменяемых read-only слоев, а запущенный container добавляет поверх них writable layer.", ["Файловые инструкции Dockerfile могут создавать новые слои image.", "Порядок инструкций влияет на cache, скорость повторной сборки и итоговый размер.", "Секреты нельзя безопасно убрать простым удалением в следующем слое."], ["docker image history IMAGE", "docker history IMAGE", "docker inspect IMAGE", "docker system df"], ["image", "dockerfile", "container", "cache", "layer"]),
  defineCard("docker-build-cache", "Кеш сборки Docker", ["docker build cache", "кеш docker build", "image cache", "сборка docker использует старый кеш", "docker no cache"], "docker", "Docker переиспользует неизменившиеся слои, чтобы ускорить сборку.", ["Сначала копируйте редко меняющиеся dependency-файлы.", "--no-cache отключает reuse слоев, но увеличивает время сборки."], ["docker build -t app .", "docker build --no-cache -t app .", "docker builder prune"], ["build", "layers", "dockerfile"]),
  defineCard("compose-ps", "Статус Compose-сервисов: docker compose ps", ["docker compose ps", "compose services status", "статус docker compose", "посмотреть контейнеры compose"], "docker", "Показывает контейнеры текущего Compose-проекта, их статус и опубликованные порты.", ["Запускайте в каталоге с compose.yaml или укажите -f.", "Для остановленных сервисов используйте --all."], ["docker compose ps", "docker compose ps --all"], ["compose", "container", "status"]),
  defineCard("compose-logs-follow", "Логи Compose в реальном времени", ["docker compose logs -f", "follow compose logs", "следить за логами compose", "логи compose онлайн"], "docker", "Объединяет и продолжает показывать новые логи сервисов Compose-проекта.", ["Можно указать один сервис, чтобы уменьшить шум.", "--tail ограничивает начальный объем."], ["docker compose logs -f --tail 100", "docker compose logs -f SERVICE"], ["compose", "logs", "service"]),
  defineCard("compose-restart", "Перезапуск Compose-сервиса", ["docker compose restart", "перезапустить compose", "restart compose service", "рестарт сервиса compose"], "docker", "Перезапускает существующие контейнеры Compose без пересоздания конфигурации.", ["Изменения compose.yaml командой restart не применяются.", "Для пересоздания используйте up -d."], ["docker compose restart", "docker compose restart SERVICE", "docker compose up -d SERVICE"], ["compose", "restart", "service"]),
  defineCard("compose-pull", "Обновление Compose images", ["docker compose pull", "compose pull", "скачать образы compose", "обновить images compose"], "docker", "Загружает новые версии images для сервисов Compose.", ["pull сам по себе не пересоздает работающие контейнеры.", "После загрузки обычно выполняют up -d."], ["docker compose pull", "docker compose up -d"], ["compose", "image", "registry"]),
  defineCard("compose-build", "Сборка Compose-сервисов", ["docker compose build", "compose build", "собрать compose", "пересобрать сервис compose"], "docker", "Собирает images сервисов, у которых указан build context.", ["--no-cache отключает кеш, --pull обновляет базовый image.", "После сборки запустите или пересоздайте сервис через up."], ["docker compose build", "docker compose build --pull SERVICE", "docker compose up -d --build"], ["compose", "build", "dockerfile"]),
  defineCard("compose-exec", "Команда внутри Compose-сервиса", ["docker compose exec", "compose exec", "зайти в compose контейнер", "выполнить команду compose"], "docker", "Запускает команду внутри уже работающего контейнера выбранного Compose-сервиса.", ["Указывается имя service из compose.yaml, а не container ID.", "Для интерактивной shell обычно достаточно exec SERVICE sh."], ["docker compose exec SERVICE sh", "docker compose exec SERVICE bash", "docker compose exec SERVICE env"], ["compose", "docker exec", "shell"]),
  defineCard("compose-config", "Проверка итоговой Compose-конфигурации", ["docker compose config", "validate compose file", "проверить compose yaml", "итоговая конфигурация compose"], "docker", "Валидирует compose.yaml и показывает конфигурацию после подстановки переменных и merge.", ["Полезно перед запуском и при неожиданных значениях environment.", "Секретные значения могут попасть в вывод терминала."], ["docker compose config", "docker compose config --services", "docker compose config --profiles"], ["compose", "yaml", "environment"]),
  defineCard("compose-environment", "Переменные окружения Docker Compose", ["compose environment variables", "переменные docker compose", "env file compose", "подстановка переменных compose"], "docker", "Compose подставляет переменные в YAML и передает environment контейнерам.", ["Файл .env для подстановки не равен env_file внутри контейнера.", "Проверяйте результат через docker compose config."], ["docker compose config", "docker compose --env-file .env.prod config", "docker compose exec SERVICE env"], ["compose", "environment", "config"]),
  defineCard("compose-volumes", "Volumes в Docker Compose", ["compose volumes", "docker compose volumes", "тома docker compose", "данные compose"], "docker", "Volumes сохраняют данные сервисов независимо от жизненного цикла контейнера.", ["Named volume создается и управляется Docker.", "down -v удаляет volumes проекта и может уничтожить данные."], ["docker compose config", "docker volume ls", "docker compose down -v"], ["compose", "volume", "storage"]),
  defineCard("compose-networks", "Networks в Docker Compose", ["compose networks", "docker compose networks", "сети docker compose", "связь сервисов compose"], "docker", "Compose подключает сервисы к сетям и дает DNS-имена по именам сервисов.", ["Сервисы в одной сети обращаются друг к другу по service name.", "Опубликованный host port для внутренней связи обычно не нужен."], ["docker compose config", "docker network ls", "docker network inspect PROJECT_default"], ["compose", "network", "dns"])
];

export const dockerTopicPack: KnowledgeTopicPack = {
  id: dockerTopicId,
  displayName: dockerDisplayName,
  cards: dockerKnowledgeCards
};
