import type { KnowledgeCard, KnowledgeTopicPack } from "./types.js";
import { defineCard } from "./types.js";

export const gitTopicId = "git" as const;
export const gitDisplayName = "Git";

export const gitKnowledgeCards: KnowledgeCard[] = [
  defineCard("git-status", "Состояние репозитория: git status", ["git status", "статус git", "что изменено git", "check git working tree"], "git", "Показывает branch, staged, unstaged и untracked files.", ["Начинайте диагностику Git почти всегда с этой команды.", "-sb дает компактный вывод."], ["git status", "git status -sb"], ["working tree", "staging", "branch"]),
  defineCard("git-add", "Добавление изменений: git add", ["git add", "добавить файлы git", "stage changes git", "git staging"], "git", "Добавляет выбранные изменения в staging area для следующего commit.", ["git add -p позволяет выбрать отдельные hunks.", "Перед commit проверьте staged diff."], ["git add FILE", "git add -p", "git diff --cached"], ["staging", "commit", "diff"]),
  defineCard("git-commit", "Создание commit: git commit", ["git commit", "создать коммит", "commit changes git", "git commit message"], "git", "Сохраняет staged snapshot в локальной истории Git.", ["Commit должен быть небольшим и логически цельным.", "Проверьте staged diff и напишите понятное сообщение."], ["git diff --cached", "git commit -m \"Describe the change\""], ["staging", "history", "message"]),
  defineCard("git-push", "Отправка commits: git push", ["git push", "отправить изменения git", "push branch", "запушить ветку"], "git", "Отправляет локальные commits и refs в remote repository.", ["Для новой branch задайте upstream через -u.", "Отклоненный push обычно требует сначала получить remote changes."], ["git push", "git push -u origin BRANCH"], ["remote", "branch", "pull"]),
  defineCard("git-pull", "Получение изменений: git pull", ["git pull", "получить изменения git", "pull changes", "обновить ветку git"], "git", "Получает remote commits и интегрирует их в текущую branch.", ["pull обычно выполняет fetch плюс merge или rebase.", "Перед операцией проверьте незакоммиченные изменения."], ["git pull --ff-only", "git pull --rebase"], ["fetch", "merge", "rebase"]),
  defineCard("git-checkout", "Переключение Git branch", ["git checkout", "git switch", "переключить ветку git", "checkout branch"], "git", "Переключает working tree на другую branch или восстанавливает выбранные files.", ["Для branch современная команда git switch яснее.", "Не переключайтесь с конфликтующими незакоммиченными изменениями."], ["git switch BRANCH", "git switch -c NEW_BRANCH", "git checkout BRANCH"], ["branch", "working tree", "switch"]),
  defineCard("git-branch", "Работа с Git branches", ["как посмотреть ветки git", "показать все ветки git", "git branch", "список веток git", "создать ветку git", "list git branches"], "git", "Показывает, создает и удаляет локальные branches.", ["Без ключей видны локальные branches, -r показывает remote-tracking branches, -a — все.", "Удаляйте branch только после проверки, что работа сохранена."], ["git branch", "git branch -a", "git branch -r", "git branch NEW_BRANCH", "git branch -d BRANCH"], ["checkout", "remote", "merge"]),
  defineCard("git-log", "История commits: git log", ["git log", "история git", "посмотреть коммиты", "git history"], "git", "Показывает commit history, авторов, даты и связи между branches.", ["--oneline удобен для краткого просмотра.", "--graph помогает увидеть merge history."], ["git log --oneline --decorate -20", "git log --graph --oneline --all", "git show COMMIT"], ["commit", "history", "branch"]),
  defineCard("git-diff", "Просмотр изменений: git diff", ["git diff", "разница git", "посмотреть изменения git", "compare git changes"], "git", "Показывает отличия working tree, staging area или commits.", ["Без аргументов показывает unstaged changes.", "--cached показывает то, что попадет в следующий commit."], ["git diff", "git diff --cached", "git diff BRANCH_A...BRANCH_B"], ["changes", "staging", "commit"]),
  defineCard("git-uncommitted-changes", "Что делать с незакоммиченными изменениями", ["fix uncommitted changes", "незакоммиченные изменения git", "cannot switch branch local changes", "сохранить изменения перед checkout"], "git", "Перед переключением или обновлением решите: commit, временно stash или осознанно отменить изменения.", ["Сначала изучите git status и diff.", "Не используйте destructive reset, пока не уверены, что изменения не нужны."], ["git status", "git diff", "git stash push -u -m \"work in progress\"", "git stash pop"], ["working tree", "stash", "checkout"]),
  defineCard("git-undo-last-commit", "Отмена последнего Git commit", ["как отменить последний commit", "как отменить последний коммит", "как откатить последний commit", "как откатить последний коммит", "undo last commit", "revert last commit"], "git", "Отменяет последний commit с выбором, сохранить ли изменения локально или создать обратный commit.", ["reset --soft снимает commit, но оставляет изменения staged; reset --mixed оставляет их unstaged.", "Для уже опубликованной общей истории безопаснее git revert HEAD, который создает новый обратный commit.", "Не переписывайте shared/pushed history без согласования с командой."], ["git reset --soft HEAD~1", "git reset --mixed HEAD~1", "git revert HEAD"], ["commit", "reset", "revert", "history"]),
  defineCard("git-pull-request", "Pull request", ["что такое pull request", "что такое пул реквест", "pull request", "пул реквест", "merge request"], "git", "Pull request — предложение влить изменения из одной branch в целевую branch.", ["Он объединяет review кода, обсуждение и результаты CI checks перед merge.", "Pull request относится к совместной работе на Git hosting и не является командой git pull."], ["git push -u origin FEATURE_BRANCH"], ["branch", "review", "merge", "ci", "collaboration"])
];

export const gitTopicPack: KnowledgeTopicPack = {
  id: gitTopicId,
  displayName: gitDisplayName,
  cards: gitKnowledgeCards
};
