import type { KnowledgeCard, KnowledgeTopicPack } from "./types.js";
import { defineCard } from "./types.js";

export const kubernetesTopicId = "kubernetes" as const;
export const kubernetesDisplayName = "Kubernetes";

export const kubernetesKnowledgeCards: KnowledgeCard[] = [
  defineCard("kubernetes-pod", "Kubernetes pod", ["kubernetes pod", "k8s pod", "под kubernetes", "что такое pod", "что такое под в kubernetes"], "kubernetes", "Минимальная единица запуска в Kubernetes: один или несколько контейнеров с общей сетью и томами.", ["Pod обычно создается контроллером, а не вручную.", "Контейнеры внутри Pod используют один IP и могут обращаться через localhost.", "Pod считается временным объектом."], ["kubectl get pods", "kubectl describe pod POD"], ["deployment", "container", "service"]),
  defineCard("kubernetes-overview", "Kubernetes: основные компоненты", ["что такое kubernetes", "из чего состоит kubernetes", "основные компоненты kubernetes", "расскажи про kubernetes", "для чего нужен kubernetes"], "kubernetes", "Kubernetes — система оркестрации контейнерных приложений в кластере.", ["Control plane хранит состояние и принимает решения через API server, scheduler и controllers.", "Worker nodes запускают Pod через kubelet и container runtime.", "Deployment управляет версиями и репликами, Service дает стабильный доступ, Ingress маршрутизирует внешний HTTP-трафик."], ["kubectl cluster-info", "kubectl get nodes", "kubectl get pods -A"], ["control plane", "node", "pod", "deployment", "service", "ingress"]),
  defineCard("kubernetes-deployment", "Kubernetes deployment", ["kubernetes deployment", "k8s deployment", "деплоймент kubernetes", "что такое deployment"], "kubernetes", "Контроллер, который поддерживает нужное число реплик Pod и выполняет обновления приложения.", ["Управляет ReplicaSet.", "Поддерживает rolling update и rollback.", "Желаемое состояние хранится в manifest."], ["kubectl get deployments", "kubectl rollout status deployment/APP", "kubectl rollout undo deployment/APP"], ["pod", "replicaset", "kubectl"]),
  defineCard("kubernetes-service", "Kubernetes service", ["kubernetes service", "k8s service", "сервис kubernetes", "что такое service kubernetes"], "kubernetes", "Стабильная виртуальная точка доступа к группе Pod, выбранных selector-ом.", ["Service отделяет клиентов от временных IP Pod.", "Частые типы: ClusterIP, NodePort и LoadBalancer."], ["kubectl get services", "kubectl describe service SERVICE"], ["pod", "ingress", "dns"]),
  defineCard("kubernetes-ingress", "Kubernetes ingress", ["kubernetes ingress", "k8s ingress", "ингресс kubernetes", "что такое ingress", "ingress"], "kubernetes", "Правила HTTP/HTTPS-маршрутизации внешнего трафика к Kubernetes Service.", ["Для работы нужен Ingress Controller.", "Обычно маршрутизирует по hostname и URL path.", "TLS настраивается через Secret и правила ingress."], ["kubectl get ingress", "kubectl describe ingress INGRESS"], ["service", "load balancer", "dns"]),
  defineCard("kubectl-get-pods", "kubectl get pods", ["kubectl get pods", "список pod kubernetes", "показать поды", "list kubernetes pods"], "kubernetes", "Показывает Pod, их готовность, статус, перезапуски и возраст.", ["-A показывает все namespaces.", "-o wide добавляет node, IP и другие детали."], ["kubectl get pods", "kubectl get pods -A -o wide"], ["pod", "kubectl-describe", "kubectl-logs"]),
  defineCard("kubectl-describe", "kubectl describe", ["kubectl describe", "описание ресурса kubernetes", "describe pod"], "kubernetes", "Показывает подробное состояние ресурса и связанные события Kubernetes.", ["Особенно полезно при Pending, CrashLoopBackOff и ошибках scheduling.", "События внизу часто объясняют причину проблемы."], ["kubectl describe pod POD", "kubectl describe deployment APP"], ["kubectl-get-pods", "events"]),
  defineCard("kubectl-logs", "kubectl logs", ["kubectl logs", "логи pod kubernetes", "логи kubernetes", "pod logs", "как посмотреть логи pod", "как посмотреть логи kubernetes"], "kubernetes", "Читает stdout и stderr контейнера внутри Pod.", ["Для нескольких контейнеров укажите -c.", "--previous показывает логи предыдущего упавшего контейнера."], ["kubectl logs POD", "kubectl logs -f POD -c CONTAINER", "kubectl logs POD --previous"], ["pod", "kubectl-describe", "logs"]),
  defineCard("kubernetes-basic-commands", "Основные команды Kubernetes и kubectl", ["основные команды kubernetes", "перечислите основные команды kubernetes", "перечисли основные команды kubernetes", "какие основные команды kubernetes", "какие основные команды вы знаете kubernetes", "какие команды вы знаете kubernetes", "команды kubectl", "основные команды kubectl", "покажи команды kubernetes", "kubernetes basic commands", "kubectl basic commands"], "kubernetes", "Короткий набор kubectl-команд для просмотра ресурсов, диагностики и применения конфигурации.", ["Перед изменениями проверьте текущий context и namespace.", "Для диагностики обычно начинают с get, затем describe и logs.", "apply изменяет состояние кластера, поэтому сначала проверьте manifest и выбранный context."], ["kubectl config current-context", "kubectl get pods -A", "kubectl get svc -A", "kubectl describe pod POD -n NAMESPACE", "kubectl logs POD -n NAMESPACE", "kubectl apply -f manifest.yaml"], ["kubectl", "pod", "service", "namespace", "context"]),
  defineCard("kubectl-get-svc", "Просмотр Kubernetes Service: kubectl get svc", ["kubectl get svc", "kubectl get services", "показать сервисы kubernetes", "list kubernetes services"], "kubernetes", "Показывает Service, их ClusterIP, внешние адреса и опубликованные порты.", ["-A выводит сервисы всех namespaces.", "EXTERNAL-IP может оставаться pending без поддерживаемого LoadBalancer."], ["kubectl get svc", "kubectl get svc -A -o wide"], ["kubernetes service", "namespace", "ingress"]),
  defineCard("kubectl-exec", "Выполнение команды в Pod: kubectl exec", ["kubectl exec", "зайти в pod", "выполнить команду в pod", "shell in kubernetes pod", "execute in pod"], "kubernetes", "Запускает команду внутри контейнера работающего Pod.", ["Для нескольких контейнеров укажите -c.", "Разделитель -- отделяет параметры kubectl от команды контейнера."], ["kubectl exec -it POD -- sh", "kubectl exec POD -c CONTAINER -- env"], ["pod", "kubectl logs", "container"]),
  defineCard("kubectl-apply", "Применение manifest: kubectl apply", ["kubectl apply", "применить manifest kubernetes", "apply yaml kubernetes", "deploy kubernetes yaml"], "kubernetes", "Создает или обновляет Kubernetes-ресурсы декларативно из YAML-файла.", ["Сначала можно выполнить server-side dry-run.", "Храните manifests в системе контроля версий."], ["kubectl apply -f manifest.yaml", "kubectl apply -f manifest.yaml --dry-run=server"], ["manifest", "kubectl delete", "deployment"]),
  defineCard("kubectl-delete", "Удаление ресурса: kubectl delete", ["kubectl delete", "удалить ресурс kubernetes", "delete kubernetes resource", "remove kubernetes pod"], "kubernetes", "Удаляет выбранный Kubernetes-ресурс по имени или manifest-файлу.", ["Контроллер может немедленно пересоздать удаленный Pod.", "Всегда проверяйте namespace перед удалением."], ["kubectl delete pod POD", "kubectl delete -f manifest.yaml"], ["kubectl apply", "namespace", "controller"]),
  defineCard("kubectl-rollout-restart", "Перезапуск Deployment: kubectl rollout restart", ["kubectl rollout restart", "перезапустить deployment", "как перезапустить kubernetes", "как перезапустить deployment kubernetes", "как перезапустить pod kubernetes", "например как перезапустить kubernetes", "restart kubernetes deployment", "restart pods deployment"], "kubernetes", "Запускает новый rollout Deployment без изменения image.", ["Pod заменяются постепенно согласно стратегии Deployment.", "После запуска проверьте rollout status."], ["kubectl rollout restart deployment/APP", "kubectl rollout restart deployment/APP -n NAMESPACE"], ["deployment", "kubectl rollout status", "pod"]),
  defineCard("kubectl-rollout-status", "Статус обновления: kubectl rollout status", ["kubectl rollout status", "проверить rollout kubernetes", "статус deployment kubernetes", "check rollout status"], "kubernetes", "Ожидает завершения rollout и сообщает об успешном обновлении или проблеме.", ["При зависании проверьте Pod и события Deployment.", "Команда подходит для CI/CD после apply."], ["kubectl rollout status deployment/APP", "kubectl rollout history deployment/APP"], ["deployment", "kubectl rollout restart", "kubectl describe"]),
  defineCard("kubectl-port-forward", "Локальный доступ: kubectl port-forward", ["kubectl port-forward", "проброс порта kubernetes", "доступ к pod локально", "forward kubernetes port"], "kubernetes", "Проксирует локальный TCP-порт к Pod или Service для диагностики.", ["Соединение работает, пока запущена команда.", "Это инструмент диагностики, а не постоянная публикация сервиса."], ["kubectl port-forward pod/POD 8080:80", "kubectl port-forward service/SERVICE 8080:80"], ["pod", "service", "port"]),
  defineCard("kubernetes-namespace", "Namespaces в Kubernetes", ["kubernetes namespace", "kubectl namespace", "пространство имен kubernetes", "namespace basics", "switch namespace"], "kubernetes", "Логически разделяют ресурсы одного кластера между командами или окружениями.", ["Большинство kubectl-команд принимают -n NAMESPACE.", "Текущий namespace можно сохранить в context."], ["kubectl get namespaces", "kubectl get pods -n NAMESPACE", "kubectl config set-context --current --namespace=NAMESPACE"], ["context", "kubectl", "cluster"]),
  defineCard("kubernetes-context", "Contexts в kubectl", ["kubectl context", "kubernetes context", "сменить контекст kubectl", "context basics", "switch kubernetes cluster"], "kubernetes", "Context объединяет кластер, пользователя и namespace для команд kubectl.", ["Перед изменениями всегда проверяйте текущий context.", "Ошибка context может направить команду в другой кластер."], ["kubectl config current-context", "kubectl config get-contexts", "kubectl config use-context CONTEXT"], ["namespace", "kubeconfig", "cluster"]),
  defineCard("kubectl-get-pods-all", "Pod во всех namespaces: kubectl get pods -A", ["kubectl get pods -a", "kubectl get pods --all-namespaces", "поды во всех namespaces", "all kubernetes pods"], "kubernetes", "Показывает Pod во всем кластере, а не только в текущем namespace.", ["Добавьте -o wide для node и Pod IP.", "Для поиска проблем удобно фильтровать строки по статусу."], ["kubectl get pods -A", "kubectl get pods -A -o wide"], ["pod", "namespace", "kubectl"]),
  defineCard("kubectl-get-nodes", "Проверка Kubernetes nodes", ["kubectl get nodes", "список нод kubernetes", "check kubernetes nodes", "статус nodes k8s"], "kubernetes", "Показывает готовность, роли и версии узлов кластера.", ["NotReady требует проверки conditions, kubelet и сети node.", "-o wide показывает внутренние адреса и runtime."], ["kubectl get nodes", "kubectl get nodes -o wide", "kubectl describe node NODE"], ["node", "kubelet", "cluster"]),
  defineCard("kubectl-logs-follow", "Логи Pod в реальном времени: kubectl logs -f", ["kubectl logs -f", "follow kubernetes logs", "следить за логами pod", "логи пода онлайн"], "kubernetes", "Продолжает читать новые stdout/stderr строки контейнера в Pod.", ["Для Pod с несколькими контейнерами укажите -c.", "При рестарте контейнера используйте --previous для прошлых логов."], ["kubectl logs -f POD", "kubectl logs -f POD -c CONTAINER", "kubectl logs POD --previous"], ["pod", "logs", "container"]),
  defineCard("kubectl-events", "События Kubernetes: kubectl get events", ["kubectl get events", "как посмотреть события kubernetes", "kubernetes events", "события k8s", "cluster events"], "kubernetes", "Показывает события scheduler, kubelet, controllers и других компонентов.", ["Сортировка по времени помогает увидеть свежую причину сбоя.", "События имеют ограниченный срок хранения."], ["kubectl get events -A --sort-by=.metadata.creationTimestamp", "kubectl get events --field-selector involvedObject.name=POD"], ["events", "describe", "troubleshooting"]),
  defineCard("kubectl-top-pods", "Ресурсы Pod: kubectl top pods", ["kubectl top pods", "нагрузка pod", "cpu memory pods", "ресурсы pod kubernetes"], "kubernetes", "Показывает текущее потребление CPU и памяти Pod через Metrics Server.", ["Команда требует работающий Metrics Server.", "Сравнивайте usage с requests и limits."], ["kubectl top pods", "kubectl top pods -A --containers"], ["metrics", "cpu", "memory"]),
  defineCard("kubectl-top-nodes", "Ресурсы nodes: kubectl top nodes", ["kubectl top nodes", "нагрузка нод kubernetes", "node cpu memory k8s", "ресурсы nodes"], "kubernetes", "Показывает CPU и память Kubernetes nodes через Metrics Server.", ["Высокий процент может объяснить pressure и проблемы scheduling.", "Подробные conditions смотрите через describe node."], ["kubectl top nodes", "kubectl describe node NODE"], ["metrics", "node", "capacity"]),
  defineCard("kubectl-current-context", "Текущий kubectl context", ["kubectl config current-context", "current kubectl context", "какой кластер kubectl", "проверить текущий context"], "kubernetes", "Показывает, к какому cluster/user/namespace сейчас обращается kubectl.", ["Проверяйте context перед apply или delete.", "Переключение выполняется через use-context."], ["kubectl config current-context", "kubectl config get-contexts", "kubectl config use-context CONTEXT"], ["context", "kubeconfig", "cluster"]),
  defineCard("kubernetes-crashloopbackoff", "Диагностика CrashLoopBackOff", ["crashloopbackoff", "pod crashloopbackoff", "pod не запускается", "под постоянно перезапускается", "kubernetes container crash loop"], "kubernetes", "CrashLoopBackOff означает, что контейнер запускается, падает и Kubernetes увеличивает паузу перед повтором.", ["Проверьте current и previous logs, exit code, events и probes.", "Частые причины: неверная команда, config, secret, зависимость или liveness probe."], ["kubectl describe pod POD", "kubectl logs POD --previous", "kubectl get pod POD -o jsonpath='{.status.containerStatuses[*].state}'"], ["pod", "logs", "probes"]),
  defineCard("kubernetes-imagepullbackoff", "Диагностика ImagePullBackOff", ["imagepullbackoff", "errimagepull", "pod не скачивает image", "ошибка загрузки образа kubernetes", "image pull error k8s"], "kubernetes", "Kubernetes не может загрузить container image и откладывает повторные попытки.", ["Проверьте имя/tag image, доступ к registry, DNS и imagePullSecrets.", "События Pod обычно содержат точный ответ registry."], ["kubectl describe pod POD", "kubectl get pod POD -o jsonpath='{.spec.containers[*].image}'", "kubectl get secret"], ["pod", "registry", "secret"]),
  defineCard("kubernetes-service-types", "Service types: ClusterIP, NodePort, LoadBalancer", ["clusterip nodeport loadbalancer", "kubernetes service types", "типы service kubernetes", "разница clusterip nodeport loadbalancer"], "kubernetes", "Тип Service определяет способ доступа к группе Pod.", ["ClusterIP доступен внутри cluster; NodePort публикует порт на nodes.", "LoadBalancer просит внешнюю интеграцию создать балансировщик."], ["kubectl get svc", "kubectl describe svc SERVICE"], ["service", "network", "load balancer"]),
  defineCard("kubernetes-configmap", "Основы Kubernetes ConfigMap", ["kubernetes configmap", "configmap basics", "что такое configmap", "конфигурация kubernetes"], "kubernetes", "ConfigMap хранит несекретную конфигурацию отдельно от container image.", ["Данные подключаются как environment или files.", "Изменение ConfigMap не всегда автоматически перезапускает Pod."], ["kubectl get configmap", "kubectl describe configmap NAME", "kubectl create configmap NAME --from-file=config.yaml"], ["configuration", "pod", "secret"]),
  defineCard("kubernetes-secret", "Основы Kubernetes Secret", ["kubernetes secret", "secret basics", "что такое secret kubernetes", "секреты k8s"], "kubernetes", "Secret передает чувствительные значения Pod через environment или volumes.", ["Base64 encoding не является шифрованием.", "Ограничьте RBAC-доступ и настройте encryption at rest при необходимости."], ["kubectl get secrets", "kubectl describe secret NAME", "kubectl create secret generic NAME --from-literal=key=value"], ["security", "configmap", "rbac"]),
  defineCard("kubernetes-probes", "Liveness и readiness probes", ["liveness readiness probes", "kubernetes probes", "liveness probe", "readiness probe", "проверки здоровья pod"], "kubernetes", "Probes определяют, когда контейнер перезапустить и когда Pod готов принимать трафик.", ["Liveness отвечает за рестарт; readiness — за участие в Service endpoints.", "Слишком строгие значения могут вызвать искусственный CrashLoop."], ["kubectl describe pod POD", "kubectl get pod POD -o yaml"], ["healthcheck", "pod", "service"])
];

export const kubernetesTopicPack: KnowledgeTopicPack = {
  id: kubernetesTopicId,
  displayName: kubernetesDisplayName,
  cards: kubernetesKnowledgeCards
};
