import type { KnowledgeCard, KnowledgeTopicPack } from "./types.js";
import { defineCard } from "./types.js";

export const linuxTopicId = "linux" as const;
export const linuxDisplayName = "Linux";

export const linuxKnowledgeCards: KnowledgeCard[] = [
  defineCard("linux-open-ports", "Проверка открытых портов в Linux", ["check open ports in linux", "как проверить открытые порты linux", "как проверить открытые порты в linux", "как проверить порт", "как проверить порт в linux", "как проверить порты в linux", "проверить порт linux", "проверить порты linux", "какие порты открыты в linux", "посмотреть открытые порты", "открытые порты linux", "listening ports linux"], "linux", "Показывает, какие процессы слушают сетевые порты и какие соединения активны.", ["Для новых систем обычно используют ss.", "Ключи -lntup показывают listening TCP/UDP-порты и процессы.", "Для проверки доступности извне дополнительно учитывайте firewall."], ["sudo ss -lntup", "sudo lsof -i -P -n"], ["ss", "netstat", "port"]),
  defineCard("linux-ss", "Команда ss", ["ss command", "команда ss", "ss -lntup", "socket statistics", "listening ports with ss", "проверить слушающие порты ss"], "linux", "Современная Linux-утилита для просмотра сокетов, портов и сетевых соединений.", ["Работает быстрее netstat на больших системах.", "Может показывать TCP, UDP, listening-сокеты и связанные процессы."], ["ss -lnt", "sudo ss -lntup"], ["netstat", "port", "linux-open-ports"]),
  defineCard("linux-netstat", "Команда netstat", ["netstat command", "команда netstat", "netstat -tulpn"], "linux", "Классическая утилита для сетевых соединений и таблиц маршрутизации; на новых Linux часто заменена на ss.", ["Полезна на старых системах и в знакомых runbook.", "Пакет net-tools может быть не установлен по умолчанию."], ["sudo netstat -tulpn", "netstat -rn"], ["ss", "routing", "port"]),
  defineCard("linux-journalctl", "journalctl", ["journalctl command", "команда journalctl", "systemd logs", "логи systemd", "journalctl -u"], "linux", "Читает системный журнал systemd и логи служб.", ["Фильтрует записи по unit, времени и приоритету.", "Ключ -f показывает новые записи в реальном времени."], ["journalctl -u nginx --since today", "journalctl -f", "journalctl -p err -b"], ["systemctl", "logs", "systemd"]),
  defineCard("linux-systemctl", "systemctl", ["systemctl command", "команда systemctl", "systemd service", "управление сервисами linux"], "linux", "Управляет службами и другими unit-объектами systemd.", ["Основные действия: status, start, stop, restart, enable.", "enable включает автозапуск, но не обязательно запускает сервис прямо сейчас."], ["systemctl status nginx", "sudo systemctl restart nginx", "sudo systemctl enable --now nginx"], ["journalctl", "systemd", "service"]),
  defineCard("linux-df", "df -h", ["df -h", "df -h command", "команда df -h", "команда linux посмотреть место на диске", "как посмотреть место на диске", "как проверить свободное место", "проверить свободное место", "проверить место на диске", "проверить место на диске linux", "disk space linux"], "linux", "Показывает использование файловых систем в удобных для чтения единицах.", ["Смотрите столбцы Size, Used, Avail и Use%.", "df показывает файловые системы, а du помогает найти крупные каталоги."], ["df -h", "du -sh /var/* | sort -h"], ["disk", "filesystem", "du"]),
  defineCard("linux-free", "free -h", ["free -h command", "команда free -h", "память linux", "linux memory usage"], "linux", "Показывает использование оперативной памяти и swap в Linux.", ["Поле available обычно полезнее, чем просто free.", "Linux использует свободную память под кеш и освобождает ее при необходимости."], ["free -h", "watch -n 2 free -h"], ["memory", "swap", "linux"]),
  defineCard("linux-systemctl-status", "Проверка статуса сервиса через systemctl", ["systemctl status", "как проверить статус сервиса", "проверить статус службы linux", "check service status", "service status linux"], "linux", "Показывает, запущен ли systemd-сервис, его PID, последние события и причину сбоя.", ["Используйте точное имя unit, обычно с суффиксом .service.", "Строки Active и Loaded дают быстрый ответ о состоянии и автозапуске."], ["systemctl status nginx", "systemctl is-active nginx", "systemctl is-enabled nginx"], ["systemctl", "journalctl", "systemd"]),
  defineCard("linux-systemctl-restart", "Перезапуск сервиса через systemctl", ["systemctl restart", "как перезапустить сервис", "перезапустить службу linux", "restart service linux", "restart systemd service"], "linux", "Останавливает и снова запускает systemd-сервис, например после изменения конфигурации.", ["Сначала по возможности проверьте конфигурацию приложения.", "После рестарта проверьте status и журнал сервиса."], ["sudo systemctl restart nginx", "systemctl status nginx --no-pager"], ["systemctl", "journalctl", "service status"]),
  defineCard("linux-journalctl-service", "Просмотр логов сервиса через journalctl", ["journalctl -u", "как посмотреть логи сервиса", "посмотреть логи службы", "логи сервиса linux", "view service logs", "service logs journalctl"], "linux", "Фильтрует системный журнал по конкретному systemd unit.", ["--since ограничивает период и уменьшает шум.", "-n показывает заданное число последних строк."], ["journalctl -u nginx --since today", "journalctl -u nginx -n 100 --no-pager"], ["journalctl", "systemctl", "logs"]),
  defineCard("linux-journalctl-follow", "Просмотр логов в реальном времени: journalctl -f", ["journalctl -f", "следить за логами сервиса", "логи в реальном времени linux", "follow service logs", "tail systemd logs"], "linux", "Показывает новые записи журнала по мере их появления.", ["Добавьте -u UNIT, чтобы следить только за нужным сервисом.", "Остановите просмотр сочетанием Ctrl+C."], ["journalctl -f", "journalctl -fu nginx"], ["journalctl", "service logs", "systemd"]),
  defineCard("linux-find-large-files", "Поиск больших файлов в Linux", ["найти большие файлы", "как найти большие файлы linux", "find large files", "largest files linux", "du sort files"], "linux", "Помогает быстро найти файлы и каталоги, которые занимают много дискового пространства.", ["du удобен для каталогов, find — для отдельных файлов.", "Запускайте поиск с нужной точки, чтобы не сканировать всю систему без необходимости."], ["sudo du -ah /var | sort -h | tail -20", "sudo find /var -type f -size +500M -printf '%s %p\\n' | sort -n"], ["df -h", "du", "filesystem"]),
  defineCard("linux-processes", "Проверка CPU и процессов: top, htop, ps", ["top command", "htop command", "ps aux", "проверить процессы linux", "нагрузка cpu linux", "check cpu processes", "process list linux"], "linux", "Показывает процессы, загрузку CPU, память и состояние системы.", ["top доступен почти всегда, htop удобнее интерактивно.", "ps полезен для разового фильтруемого снимка."], ["top", "htop", "ps aux --sort=-%cpu | head"], ["process", "cpu", "free -h"]),
  defineCard("linux-kill-process", "Завершение процесса в Linux", ["kill process", "kill command", "как завершить процесс linux", "убить процесс linux", "terminate process linux"], "linux", "Отправляет процессу сигнал завершения по PID или имени.", ["Начинайте с обычного SIGTERM, чтобы процесс завершился корректно.", "SIGKILL (-9) используйте только если процесс не реагирует."], ["kill PID", "pkill PROCESS_NAME", "kill -9 PID"], ["ps", "top", "process"]),
  defineCard("linux-ip-addr", "Проверка IP-адресов: ip addr", ["ip addr", "ip address linux", "как проверить ip адрес linux", "показать ip linux", "check ip address linux"], "linux", "Показывает сетевые интерфейсы, назначенные IPv4/IPv6-адреса и состояние link.", ["Краткий вывод удобнее смотреть с ключом -br.", "Адрес 127.0.0.1 относится к loopback, а не к внешнему интерфейсу."], ["ip addr", "ip -br addr"], ["ip route", "interface", "networking"]),
  defineCard("linux-ip-route", "Проверка маршрутов: ip route", ["ip route", "route table linux", "как проверить маршруты linux", "таблица маршрутизации linux", "check routes linux"], "linux", "Показывает таблицу маршрутизации и default gateway Linux.", ["Маршрут default используется, когда более точного маршрута нет.", "Команда route устарела; обычно применяют ip route."], ["ip route", "ip route get 8.8.8.8"], ["ip addr", "gateway", "traceroute"]),
  defineCard("linux-ls-permissions", "Проверка прав доступа: ls -l", ["ls -l", "проверить права файла linux", "посмотреть permissions linux", "check file permissions", "linux permissions"], "linux", "Показывает тип объекта, права владельца, группы и остальных пользователей.", ["Первые символы выглядят как -rwxr-xr--.", "Дальше указаны владелец и группа объекта."], ["ls -l FILE", "namei -l /path/to/file"], ["chmod", "chown", "permissions"]),
  defineCard("linux-chmod", "Изменение прав доступа: chmod", ["chmod", "chmod command", "chmod +x", "команда linux задать права на исполнение", "права на исполнение файла", "права на исполнение файла командной строки", "как сделать файл исполняемым", "как выдать права на файл", "изменить права linux", "change permissions linux", "chmod 755"], "linux", "Меняет права чтения, записи и выполнения для владельца, группы и остальных.", ["Числа 7, 5 и 4 соответствуют комбинациям rwx, r-x и r--.", "Не назначайте 777 без явной необходимости: это дает запись всем пользователям."], ["chmod +x SCRIPT", "chmod 644 FILE", "chmod 755 SCRIPT", "chmod u+x SCRIPT"], ["ls -l", "chown", "permissions"]),
  defineCard("linux-chown", "Изменение владельца: chown", ["chown", "chown command", "изменить владельца файла", "change file owner linux", "change ownership linux"], "linux", "Меняет владельца и группу файла или каталога.", ["Ключ -R применяет изменение рекурсивно и требует осторожности: неверный owner может сломать сервис или открыть доступ.", "После изменения проверьте результат через ls -l."], ["sudo chown USER:GROUP FILE", "sudo chown -R USER:GROUP DIRECTORY"], ["ls -l", "chmod", "ownership"]),
  defineCard("linux-file-directory-permissions", "Права файлов и каталогов: chmod и chown", ["как повысить права файлов", "как повысить права файла", "как повысить права файлов в linux", "как изменить права файла", "как изменить права директории", "как повысить права директории", "как дать права на папку", "как дать права на файл", "как сделать файл исполняемым", "как изменить владельца файла"], "linux", "Права Linux разделяют чтение, запись и выполнение для владельца, группы и остальных; chmod меняет mode, а chown — владельца и группу.", ["Сначала проверьте текущие права и ownership через ls -l.", "Для каталогов execute означает возможность входа и доступа к объектам внутри.", "Не используйте chmod 777 как универсальное исправление: выдавайте только необходимый доступ."], ["ls -l FILE", "chmod +x script.sh", "chmod 640 FILE", "chmod 750 DIRECTORY", "chown USER:GROUP FILE", "chown -R USER:GROUP DIRECTORY"], ["chmod", "chown", "file permissions", "directory permissions", "ownership"]),
  defineCard("linux-mount", "Подключение дисков: mount", ["mount disk linux", "команда mount", "как смонтировать диск", "подключить диск linux", "mount filesystem"], "linux", "Подключает файловую систему устройства к каталогу в дереве Linux.", ["Перед mount создайте точку монтирования.", "Для постоянного подключения добавляют запись в /etc/fstab."], ["lsblk -f", "sudo mount /dev/sdb1 /mnt/data", "mount | grep /mnt/data"], ["fstab", "lsblk", "filesystem"]),
  defineCard("linux-fstab", "Проверка /etc/fstab", ["fstab", "/etc/fstab", "проверить fstab", "настроить автомонтирование linux", "check fstab", "persistent mount linux"], "linux", "Файл /etc/fstab описывает файловые системы, которые должны монтироваться автоматически.", ["Предпочтительно использовать UUID вместо /dev/sdX.", "Проверяйте конфигурацию командой mount -a до перезагрузки."], ["cat /etc/fstab", "lsblk -f", "sudo mount -a"], ["mount", "uuid", "filesystem"]),
  defineCard("linux-failed-services", "Проверка упавших systemd-сервисов", ["systemctl failed", "systemctl --failed", "check failed systemd services", "проверить упавшие сервисы", "какие сервисы упали linux"], "linux", "Показывает systemd units, которые завершились с ошибкой.", ["Начните со списка failed units, затем откройте status и журнал конкретного сервиса.", "После исправления причины сбросьте старое failed-состояние."], ["systemctl --failed", "systemctl status SERVICE", "sudo systemctl reset-failed SERVICE"], ["systemctl", "journalctl", "systemd"]),
  defineCard("linux-journalctl-xe", "Диагностика ошибок: journalctl -xe", ["journalctl -xe", "последние ошибки linux", "systemd recent errors", "как посмотреть системные ошибки linux"], "linux", "Показывает последние записи systemd journal с пояснениями и важными событиями.", ["Полезно сразу после неудачного запуска службы или системной операции.", "Для точной службы обычно лучше добавить фильтр -u."], ["sudo journalctl -xe", "sudo journalctl -xeu SERVICE"], ["journalctl", "systemctl", "logs"]),
  defineCard("linux-boot-logs", "Проверка логов загрузки Linux", ["journalctl -b", "check boot logs", "логи загрузки linux", "как посмотреть логи загрузки", "ошибки при загрузке linux"], "linux", "Фильтрует journal по текущей или предыдущей загрузке системы.", ["-b показывает текущую загрузку, -b -1 — предыдущую.", "Добавьте -p err для ошибок высокого приоритета."], ["journalctl -b", "journalctl -b -1", "journalctl -b -p err"], ["journalctl", "boot", "systemd"]),
  defineCard("linux-inodes", "Проверка использования inode", ["df -i", "check inode usage", "проверить inode", "закончились inode", "место есть но файл не создается"], "linux", "Показывает, не исчерпано ли количество inode при наличии свободного места в гигабайтах.", ["Большое число мелких файлов может занять все inode.", "После обнаружения найдите каталоги с наибольшим количеством файлов."], ["df -i", "find /var -xdev -type f | wc -l", "du --inodes -d 2 /var | sort -n"], ["df", "filesystem", "find"]),
  defineCard("linux-swap", "Проверка использования swap", ["check swap usage", "проверить swap", "swap linux", "swapon --show", "как посмотреть swap"], "linux", "Показывает настроенный swap и текущую активность подкачки.", ["Небольшое использование swap само по себе не означает проблему.", "Смотрите вместе с available memory и нагрузкой ввода-вывода."], ["free -h", "swapon --show", "vmstat 1"], ["memory", "free", "vmstat"]),
  defineCard("linux-cpu-load", "Проверка нагрузки CPU и load average", ["как посмотреть нагрузку", "проверить нагрузку linux", "check cpu load", "load average linux", "uptime load"], "linux", "Показывает load average и процессы, потребляющие CPU.", ["Load average сравнивайте с количеством CPU cores.", "Высокий load может быть вызван не только CPU, но и ожиданием I/O."], ["uptime", "top", "ps aux --sort=-%cpu | head"], ["cpu", "top", "processes"]),
  defineCard("linux-firewall-status", "Проверка firewall в Linux", ["check firewall status linux", "проверить firewall linux", "проверить firewall", "статус firewall", "статус фаервола", "какой firewall работает", "ufw status", "firewall-cmd --state", "iptables -l"], "linux", "Помогает определить активный firewall и текущие правила фильтрации.", ["На разных системах используются firewalld, nftables, iptables или ufw.", "Проверяйте и правила, и факт прослушивания порта приложением."], ["sudo ufw status verbose", "sudo firewall-cmd --state", "sudo iptables -L -n -v", "sudo nft list ruleset"], ["firewalld", "iptables", "nftables", "port"]),
  defineCard("linux-firewalld", "Основы firewalld", ["firewalld basics", "firewall-cmd", "настроить firewalld", "открыть порт firewalld", "проверить правила firewalld"], "linux", "firewalld управляет зонами и правилами firewall через firewall-cmd.", ["Временные правила исчезают после перезапуска.", "Для постоянного правила используйте --permanent и затем reload."], ["sudo firewall-cmd --list-all", "sudo firewall-cmd --add-port=8080/tcp --permanent", "sudo firewall-cmd --reload"], ["firewall", "port", "zones"]),
  defineCard("linux-iptables", "Основы iptables", ["iptables basics", "iptables command", "iptables -l", "проверить iptables", "правила iptables", "открыть порт iptables"], "linux", "iptables просматривает и изменяет правила фильтрации пакетов в ядре Linux.", ["Сначала смотрите цепочки INPUT, OUTPUT и FORWARD.", "На новых системах команды могут работать через backend nftables."], ["sudo iptables -L -n -v --line-numbers", "sudo iptables -S", "sudo iptables -t nat -L -n -v"], ["firewall", "nftables", "nat"]),
  defineCard("linux-selinux", "Проверка состояния SELinux", ["getenforce", "sestatus", "check selinux status", "проверить selinux", "selinux блокирует"], "linux", "Показывает режим SELinux и помогает выявить блокировки политики безопасности.", ["Enforcing применяет правила, Permissive только журналирует нарушения.", "Не отключайте SELinux до проверки audit log и контекста файла."], ["getenforce", "sestatus", "sudo ausearch -m AVC -ts recent"], ["security", "audit", "permissions"]),
  defineCard("linux-users", "Проверка пользователей в Linux", ["check users linux", "посмотреть пользователей linux", "список пользователей", "who command", "кто вошел linux"], "linux", "Показывает учетные записи и активные пользовательские сессии.", ["/etc/passwd содержит локальные учетные записи.", "who и w показывают текущие входы и активность."], ["cut -d: -f1 /etc/passwd", "who", "w", "id USER"], ["users", "groups", "authentication"]),
  defineCard("linux-sudo-permissions", "Проверка прав sudo", ["sudo -l", "check sudo permissions", "проверить права sudo", "что может sudo пользователь", "sudoers permissions"], "linux", "Показывает, какие команды пользователь может запускать через sudo.", ["sudo -l проверяет эффективные правила текущего пользователя.", "Файлы sudoers редактируйте через visudo, чтобы проверить синтаксис."], ["sudo -l", "sudo -l -U USER", "sudo visudo -c"], ["sudoers", "users", "permissions"]),
  defineCard("linux-permissions-overview", "Права в Linux: chmod, chown и sudo", ["как дать права в linux", "как дать права в линукс", "дать права linux", "дать права линукс", "как выдать права в linux", "как выдать права в линукс", "права в linux", "права в линукс", "как дать права пользователю linux", "как дать права пользователю в linux", "как дать права пользователю в линукс", "как выдать права пользователю linux", "как выдать права пользователю в linux", "как выдать права пользователю в линукс", "linux permissions", "chmod chown sudo"], "linux", "Фраза «дать права» в Linux может означать права файла через chmod, смену владельца через chown или административный доступ через sudo и группы.", ["Для файла или каталога сначала проверьте текущие права и владельца, затем меняйте только нужный доступ.", "Для административных прав добавьте пользователя в sudo или wheel и проверьте его группы после нового входа.", "Точные правила sudoers редактируйте через visudo, чтобы не повредить конфигурацию."], ["ls -l file", "chmod +x script.sh", "chmod 755 script.sh", "chown user:group file", "usermod -aG sudo username", "usermod -aG wheel username", "groups username", "id username", "visudo"], ["chmod", "chown", "sudo", "sudoers", "file permissions", "user groups"]),
  defineCard("linux-security-quick-check", "Быстрая проверка безопасности Linux", ["проверить безопасность linux", "как проверить безопасность в linux", "как проверить безопасность linux", "linux security quick check", "security audit linux", "базовая проверка безопасности linux"], "linux", "Короткая первичная проверка открытых портов, firewall, ошибок входа и привилегий.", ["Это не полноценный аудит, а безопасная стартовая выборка для поиска очевидных рисков.", "Сначала собирайте факты; не отключайте защитные механизмы только ради диагностики."], ["sudo ss -lntup", "sudo ufw status verbose", "sudo firewall-cmd --state", "sudo journalctl -p warning -b", "sudo -l"], ["firewall", "sudo", "ssh", "selinux", "open ports"]),
  defineCard("linux-sudo-basics", "Основы sudo", ["sudo basics", "что такое sudo", "права sudo", "доступ sudo", "как пользоваться sudo", "чтобы не писать sudo"], "linux", "sudo запускает отдельную команду с правами другого пользователя, обычно root, если это разрешено политикой sudoers.", ["Добавление в sudo/wheel обычно не убирает слово sudo из команды.", "NOPASSWD убирает запрос пароля, а не сам sudo, и повышает риск при слишком широких правилах."], ["sudo -l", "sudo COMMAND", "sudo -i"], ["sudoers", "users", "root", "permissions"]),
  defineCard("linux-add-user-sudo", "Добавление пользователя в sudo или wheel", ["как повысить права пользователя в linux", "как повысить привилегии пользователя", "как дать пользователю административные права", "как сделать пользователя sudo", "как дать пользователю root-права", "как дать пользователю права администратора в linux", "как добавить пользователю sudo", "как добавить пользователю права sudo", "как дать пользователю права sudo", "как добавить пользователя в sudo", "добавить пользователя в sudo", "как добавить юзера в sudo", "добавить юзера в группу sudo", "как включить пользователя в sudo", "как дать пользователю sudo", "как добавить пользователя в wheel", "добавить пользователя в группу wheel", "как добавить права пользователю чтобы не писать sudo", "как добавить пользователя права sudo", "как дать права в linux sudo", "как дать sudo пользователю", "как добавить пользователя в группу sudo", "добавить пользователя в группу sudo", "добавить пользователя в sudo group", "usermod -ag sudo", "usermod -ag wheel"], "linux", "Добавляет существующего пользователя в административную группу Debian/Ubuntu `sudo` или RHEL-подобную `wheel`.", ["Используйте -aG: без -a можно случайно удалить пользователя из остальных дополнительных групп.", "Не выдавайте unrestricted sudo без необходимости; применяйте принцип минимальных привилегий.", "После изменения проверьте membership через groups/id и правила через sudo -l или visudo."], ["sudo usermod -aG sudo USER", "sudo usermod -aG wheel USER", "groups USER", "id USER", "sudo visudo"], ["sudo", "sudoers", "wheel", "users", "groups", "root privileges"]),
  defineCard("linux-change-password", "Смена пароля пользователя в Linux", ["как поменять пароль в linux", "как поменять пароль linux", "как поменять пароль пользователя в linux", "как изменить пароль пользователя", "как сменить пароль linux", "как сменить пароль в linux", "как поменять пароль пользователю", "менять пароль в linux", "меняем пароль в linux", "команды для замены пароля в linux", "passwd", "сбросить пароль пользователя linux", "сменить пароль root"], "linux", "passwd меняет пароль текущего пользователя, а sudo passwd USER — пароль другой учетной записи.", ["Для root укажите sudo passwd root только при осознанной необходимости.", "chage показывает срок действия пароля и может потребовать смену при следующем входе.", "Не помещайте пароли напрямую в shell history или скрипты."], ["passwd", "sudo passwd USER", "sudo passwd root", "chage -l USER", "sudo chage -d 0 USER"], ["passwd", "password", "users", "chage", "authentication"]),
  defineCard("linux-sudoers-basics", "Безопасное редактирование sudoers", ["sudoers basics", "добавить пользователя в sudoers", "как добавить пользователя в sudoers", "visudo", "настроить sudoers", "sudoers.d"], "linux", "sudoers определяет, кто и какие команды может выполнять через sudo.", ["Редактируйте правила через visudo: он проверяет синтаксис до сохранения.", "Предпочитайте точные команды и отдельный файл в /etc/sudoers.d вместо широкого ALL или NOPASSWD."], ["sudo visudo", "sudo visudo -c", "sudo visudo -f /etc/sudoers.d/USER"], ["sudo", "permissions", "users", "least privilege"]),
  defineCard("linux-user-groups", "Проверка пользователя и его групп", ["проверить группы пользователя", "в каких группах пользователь", "проверить права пользователя", "id username", "groups username", "whoami groups", "whoami", "команда id пользователь"], "linux", "Показывает UID, основную и дополнительные группы пользователя, которые часто определяют доступ к файлам и sudo.", ["`id USER` удобен для полной сводки, `groups USER` — для списка групп.", "После изменения групп пользователь обычно должен войти заново, чтобы получить новый набор membership."], ["whoami", "id USER", "groups USER", "getent group sudo", "getent group wheel"], ["users", "groups", "sudo", "permissions"]),
  defineCard("linux-ssh-access", "Базовая проверка SSH-доступа", ["ssh access basics", "проверить ssh доступ", "sshd status", "authorized_keys", "permitrootlogin", "настроить ssh доступ linux", "не работает ssh вход"], "linux", "Проверяет состояние sshd, ключи пользователя и ключевые ограничения конфигурации SSH.", ["Каталог ~/.ssh обычно должен иметь режим 700, а authorized_keys — 600.", "PermitRootLogin лучше отключать или ограничивать; перед перезапуском проверяйте конфигурацию через sshd -t."], ["systemctl status sshd", "sudo sshd -t", "ls -ld ~/.ssh ~/.ssh/authorized_keys", "sudo sshd -T | grep -i permitrootlogin"], ["ssh", "authorized_keys", "firewall", "users"]),
  defineCard("linux-tar", "Создание и распаковка tar-архивов", ["tar archive", "команда tar", "создать архив linux", "распаковать tar gz", "tar examples"], "linux", "tar объединяет файлы в архив и часто используется вместе с gzip или xz.", ["-c создает архив, -x распаковывает, -t показывает содержимое.", "Перед распаковкой неизвестного архива полезно посмотреть список файлов."], ["tar -czf backup.tar.gz DIR", "tar -tzf backup.tar.gz", "tar -xzf backup.tar.gz"], ["archive", "gzip", "backup"]),
  defineCard("linux-grep", "Практические примеры grep", ["grep examples", "команда grep", "как найти строку в файле", "поиск текста linux", "grep recursive"], "linux", "grep ищет строки по тексту или регулярному выражению.", ["-i игнорирует регистр, -r ищет рекурсивно, -n показывает номера строк.", "Для логов часто полезны контекстные ключи -A, -B и -C."], ["grep -in \"error\" app.log", "grep -Rin \"listen\" /etc/nginx", "journalctl -u SERVICE | grep -i error"], ["text", "logs", "find"]),
  defineCard("linux-find", "Поиск файлов командой find", ["find command", "команда find", "как найти файл linux", "поиск файлов linux", "find examples"], "linux", "find ищет файлы по имени, типу, размеру, времени и другим признакам.", ["Ограничивайте начальный каталог, чтобы ускорить поиск.", "С -exec сначала проверьте выборку без изменяющей команды."], ["find /etc -type f -name '*.conf'", "find /var/log -type f -mtime -1", "find /tmp -type f -size +100M"], ["files", "grep", "large files"]),
  defineCard("linux-rsync", "Основы rsync", ["rsync basics", "команда rsync", "синхронизация файлов linux", "копировать через rsync", "rsync example"], "linux", "rsync эффективно синхронизирует каталоги локально или через SSH.", ["-a сохраняет основные атрибуты, -v показывает процесс.", "Перед --delete полезно выполнить dry-run."], ["rsync -avh SOURCE/ DEST/", "rsync -avhn --delete SOURCE/ DEST/", "rsync -avh DIR/ user@host:/backup/"], ["backup", "ssh", "files"]),
  defineCard("linux-cron", "Основы cron", ["cron basics", "что такое cron", "планировщик linux", "настроить cron", "cron job"], "linux", "cron запускает команды по расписанию от имени пользователя или системы.", ["Окружение cron минимально, поэтому используйте абсолютные пути.", "Перенаправляйте stdout и stderr в лог для диагностики."], ["systemctl status cron", "systemctl status crond", "journalctl -u cron"], ["crontab", "scheduler", "systemd timer"]),
  defineCard("linux-crontab", "Примеры crontab", ["crontab examples", "crontab -e", "пример crontab", "как добавить задачу cron", "посмотреть cron задачи"], "linux", "crontab хранит пользовательские задания cron в формате минута, час, день, месяц, день недели.", ["Проверьте команду вручную перед добавлением в расписание.", "crontab -l показывает задания текущего пользователя."], ["crontab -l", "crontab -e", "0 2 * * * /usr/local/bin/backup.sh >> /var/log/backup.log 2>&1"], ["cron", "scheduler", "logs"])
];

export const linuxTopicPack: KnowledgeTopicPack = {
  id: linuxTopicId,
  displayName: linuxDisplayName,
  cards: linuxKnowledgeCards
};
