import type { KnowledgeCard, KnowledgeTopicPack } from "./types.js";
import { defineCard } from "./types.js";

export const networkingTopicId = "networking" as const;
export const networkingDisplayName = "Networking";

export const networkingKnowledgeCards: KnowledgeCard[] = [
  defineCard("network-nat", "NAT", ["nat", "network address translation", "что такое nat", "трансляция сетевых адресов"], "networking", "Преобразует IP-адреса и иногда порты между сетями, часто между частной сетью и интернетом.", ["SNAT меняет адрес источника.", "DNAT меняет адрес назначения.", "PAT позволяет многим устройствам делить один внешний IP через разные порты."], ["iptables -t nat -L -n -v", "Get-NetNat"], ["port", "routing", "firewall"]),
  defineCard("network-dns", "DNS", ["dns", "domain name system", "что такое dns", "как работает dns", "система доменных имен"], "networking", "Преобразует доменные имена в IP-адреса и хранит другие записи о доменах.", ["Клиент обычно обращается к recursive resolver.", "A/AAAA указывают адрес, CNAME — псевдоним, MX — почтовый сервер.", "Кеш и TTL влияют на скорость распространения изменений."], ["nslookup example.com", "dig example.com A"], ["nslookup", "active-directory-dns", "dhcp"]),
  defineCard("network-dhcp", "DHCP", ["dhcp", "dynamic host configuration protocol", "что такое dhcp", "как работает dhcp"], "networking", "Автоматически выдает клиентам IP-настройки: адрес, маску, gateway, DNS и срок аренды.", ["Классическая последовательность: Discover, Offer, Request, Acknowledge.", "Reservation закрепляет адрес за конкретным клиентом."], ["ipconfig /all", "ipconfig /renew", "nmcli device show"], ["dns", "ip address", "dhcp-role"]),
  defineCard("network-ping", "ping", ["ping command", "команда ping", "проверить доступность хоста", "icmp ping"], "networking", "Проверяет сетевую достижимость и приблизительную задержку с помощью ICMP Echo.", ["Успешный ping не гарантирует работу нужного TCP-порта.", "ICMP может быть заблокирован firewall, даже если сервис доступен."], ["ping 8.8.8.8", "ping example.com"], ["traceroute", "dns", "port"]),
  defineCard("network-traceroute", "traceroute / tracert", ["traceroute", "tracert", "trace route", "трассировка маршрута", "как проверить маршрут"], "networking", "Показывает последовательность сетевых узлов до назначения и помогает искать участок задержки или потерь.", ["В Linux обычно используется traceroute или tracepath.", "В Windows используется tracert.", "Некоторые промежуточные узлы не отвечают на диагностические пакеты."], ["traceroute example.com", "tracert example.com"], ["ping", "routing"]),
  defineCard("network-dns-tools", "nslookup / dig", ["nslookup", "dig command", "команда dig", "проверить dns", "dns lookup"], "networking", "Диагностические утилиты для запроса DNS-записей и проверки resolver-ов.", ["nslookup доступен на Windows и многих Unix-системах.", "dig дает более подробный и скриптуемый ответ."], ["nslookup example.com", "nslookup example.com 8.8.8.8", "dig example.com +short"], ["dns", "active-directory-dns"]),
  defineCard("network-nslookup", "Проверка DNS через nslookup", ["nslookup", "nslookup command", "команда nslookup", "проверить dns запись windows", "dns lookup windows"], "networking", "Запрашивает DNS-имя или запись у системного либо указанного DNS-сервера.", ["Можно явно указать сервер вторым аргументом.", "Для подробной диагностики в Linux часто удобнее dig."], ["nslookup example.com", "nslookup example.com 8.8.8.8", "nslookup -type=MX example.com"], ["dig", "dns", "dns records"]),
  defineCard("network-dig", "Проверка DNS через dig", ["dig", "dig command", "команда dig", "проверить dns linux", "dns lookup linux"], "networking", "Показывает подробный DNS-ответ, сервер, секции и время запроса.", ["+short оставляет только краткий результат.", "Укажите @SERVER для запроса конкретного resolver."], ["dig example.com A", "dig @8.8.8.8 example.com +short", "dig example.com MX"], ["nslookup", "dns", "dns records"]),
  defineCard("network-curl", "HTTP-проверка через curl", ["curl", "curl command", "команда curl", "проверить http endpoint", "http request command"], "networking", "Отправляет HTTP-запросы и помогает проверить доступность, заголовки и ответы API.", ["-I запрашивает только заголовки.", "-v показывает детали DNS, TLS и соединения."], ["curl -I https://example.com", "curl -v http://HOST:PORT/health", "curl -sS https://example.com/api"], ["http", "tls", "port"]),
  defineCard("network-netcat", "Проверка TCP/UDP через nc (netcat)", ["nc command", "netcat", "nc -vz", "проверить порт nc", "test port netcat"], "networking", "Проверяет, устанавливается ли TCP-соединение с нужным хостом и портом.", ["-z выполняет проверку без передачи данных.", "Успех показывает доступность порта, но не корректность приложения."], ["nc -vz HOST 443", "nc -vzu HOST 53"], ["port", "telnet", "curl"]),
  defineCard("network-telnet-port", "Проверка порта через telnet", ["telnet port test", "проверить порт telnet", "telnet host port", "test tcp port telnet"], "networking", "Открывает простое TCP-соединение и может подтвердить достижимость порта.", ["Telnet-клиент может быть не установлен.", "Для автоматизации и таймаутов обычно удобнее nc или Test-NetConnection."], ["telnet HOST 443", "Test-NetConnection HOST -Port 443"], ["nc", "port", "tcp"]),
  defineCard("network-dns-records", "Типы DNS-записей: A, CNAME, MX, TXT", ["dns record types", "типы dns записей", "a cname mx txt", "dns a record", "dns cname mx txt"], "networking", "DNS-записи описывают адреса, псевдонимы, почтовые серверы и текстовые данные домена.", ["A связывает имя с IPv4, CNAME — с другим именем.", "MX задает почтовые серверы, TXT часто хранит SPF и подтверждения владения."], ["dig example.com A", "dig example.com CNAME", "dig example.com MX", "dig example.com TXT"], ["dns", "nslookup", "dig"]),
  defineCard("network-dhcp-lease", "Аренда адреса DHCP", ["dhcp lease", "аренда dhcp", "срок аренды ip", "renew dhcp lease", "dhcp lease basics"], "networking", "DHCP lease временно закрепляет IP-конфигурацию за клиентом.", ["Клиент пытается продлить lease до истечения срока.", "Reservation связывает постоянный адрес с MAC или client identifier."], ["ipconfig /all", "ipconfig /release && ipconfig /renew", "nmcli device show"], ["dhcp", "ip address", "reservation"]),
  defineCard("network-tcp-port", "Проверка TCP-порта", ["как проверить доступность порта", "проверить доступность порта", "check tcp port", "проверить tcp порт", "как проверить порт", "проверить порт host", "доступен ли порт"], "networking", "Проверяет, устанавливается ли TCP-соединение с конкретным host и port.", ["Для локального сервиса сначала проверьте, слушает ли процесс порт через ss или netstat.", "Для удаленной доступности проверяйте соединение с той же сети, где находится реальный клиент.", "Открытый TCP port не гарантирует корректный ответ приложения."], ["Test-NetConnection HOST -Port PORT", "nc -vz HOST PORT", "curl -v telnet://HOST:PORT"], ["tcp", "port", "firewall", "ss", "netstat"]),
  defineCard("network-udp", "Основы проверки UDP", ["check udp port", "проверить udp порт", "udp basics", "проверка udp", "nc udp"], "networking", "UDP не устанавливает соединение, поэтому отсутствие ответа не всегда означает закрытый порт.", ["Используйте протокольный запрос, если он известен, например DNS.", "Firewall может молча отбрасывать пакеты."], ["nc -vzu HOST 53", "dig @HOST example.com", "sudo tcpdump -ni any udp port 53"], ["udp", "dns", "firewall"]),
  defineCard("network-dns-troubleshooting", "Диагностика DNS", ["dns troubleshooting", "dns не работает", "проблемы dns", "не разрешается имя", "ошибка name resolution"], "networking", "Разделяет проблемы resolver, DNS-сервера, записи и сетевой доступности.", ["Сравните запрос к системному resolver и известному DNS-серверу.", "Проверьте suffix, search domains, кеш и правильность record type."], ["nslookup example.com", "nslookup example.com 8.8.8.8", "dig example.com +trace", "ipconfig /flushdns"], ["dns", "nslookup", "dig"]),
  defineCard("network-default-gateway", "Проверка default gateway", ["default gateway", "шлюз по умолчанию", "проверить gateway", "какой шлюз linux windows"], "networking", "Default gateway получает трафик к сетям, для которых нет более точного маршрута.", ["Сначала проверьте локальный адрес и route table.", "Недоступный gateway ломает выход за пределы локальной subnet."], ["ip route | grep default", "route print", "ipconfig /all"], ["routing", "subnet", "ip address"]),
  defineCard("network-cidr", "Subnet mask и CIDR", ["subnet mask cidr", "маска подсети", "что такое cidr", "рассчитать подсеть", "24 subnet"], "networking", "CIDR-префикс определяет сетевую и host-часть IP-адреса.", ["/24 соответствует маске 255.255.255.0.", "Устройства считают адрес локальным, если он попадает в их subnet."], ["ipcalc 192.168.1.10/24", "Get-NetIPAddress"], ["subnet", "routing", "gateway"]),
  defineCard("network-arp", "Проверка ARP-таблицы", ["arp table", "таблица arp", "проверить arp", "ip neigh", "mac адрес по ip"], "networking", "ARP/neighbor table связывает IPv4-адреса локальной сети с MAC-адресами.", ["FAILED или INCOMPLETE указывает на отсутствие L2-ответа.", "Записи динамические и могут устаревать."], ["ip neigh show", "arp -a", "Get-NetNeighbor"], ["layer 2", "mac", "gateway"]),
  defineCard("network-route-troubleshooting", "Диагностика маршрутизации", ["route troubleshooting", "не работает маршрут", "проверить маршрутизацию", "куда идет трафик", "route problem"], "networking", "Проверяет выбранный маршрут, gateway и путь пакетов до назначения.", ["Самый специфичный route имеет приоритет.", "Сравните route table, traceroute и правила firewall/NAT."], ["ip route get 8.8.8.8", "ip route", "traceroute 8.8.8.8", "route print"], ["routing", "gateway", "traceroute"])
];

export const networkingTopicPack: KnowledgeTopicPack = {
  id: networkingTopicId,
  displayName: networkingDisplayName,
  cards: networkingKnowledgeCards
};
