import { expandedKnowledgeCards } from "./knowledgeCardsExpanded.js";

export interface KnowledgeCard {
  id: string;
  title: string;
  aliases: string[];
  category: "linux" | "docker" | "kubernetes" | "networking" | "active-directory" | "proxmox" | "git";
  shortExplanation: string;
  bullets: string[];
  commands: string[];
  relatedTerms: string[];
}

const baseKnowledgeCards: KnowledgeCard[] = [
  card("linux-open-ports", "Проверка открытых портов в Linux", ["check open ports in linux", "как проверить открытые порты linux", "как проверить открытые порты в linux", "как проверить порт", "проверить порт linux", "открытые порты linux", "listening ports linux"], "linux", "Показывает, какие процессы слушают сетевые порты и какие соединения активны.", ["Для новых систем обычно используют ss.", "Ключи -lntup показывают listening TCP/UDP-порты и процессы.", "Для проверки доступности извне дополнительно учитывайте firewall."], ["sudo ss -lntup", "sudo lsof -i -P -n"], ["ss", "netstat", "port"]),
  card("linux-ss", "Команда ss", ["ss command", "команда ss", "ss -lntup", "socket statistics", "listening ports with ss", "проверить слушающие порты ss"], "linux", "Современная Linux-утилита для просмотра сокетов, портов и сетевых соединений.", ["Работает быстрее netstat на больших системах.", "Может показывать TCP, UDP, listening-сокеты и связанные процессы."], ["ss -lnt", "sudo ss -lntup"], ["netstat", "port", "linux-open-ports"]),
  card("linux-netstat", "Команда netstat", ["netstat command", "команда netstat", "netstat -tulpn"], "linux", "Классическая утилита для сетевых соединений и таблиц маршрутизации; на новых Linux часто заменена на ss.", ["Полезна на старых системах и в знакомых runbook.", "Пакет net-tools может быть не установлен по умолчанию."], ["sudo netstat -tulpn", "netstat -rn"], ["ss", "routing", "port"]),
  card("linux-journalctl", "journalctl", ["journalctl command", "команда journalctl", "systemd logs", "логи systemd", "journalctl -u"], "linux", "Читает системный журнал systemd и логи служб.", ["Фильтрует записи по unit, времени и приоритету.", "Ключ -f показывает новые записи в реальном времени."], ["journalctl -u nginx --since today", "journalctl -f", "journalctl -p err -b"], ["systemctl", "logs", "systemd"]),
  card("linux-systemctl", "systemctl", ["systemctl command", "команда systemctl", "systemd service", "управление сервисами linux"], "linux", "Управляет службами и другими unit-объектами systemd.", ["Основные действия: status, start, stop, restart, enable.", "enable включает автозапуск, но не обязательно запускает сервис прямо сейчас."], ["systemctl status nginx", "sudo systemctl restart nginx", "sudo systemctl enable --now nginx"], ["journalctl", "systemd", "service"]),
  card("linux-df", "df -h", ["df -h", "df -h command", "команда df -h", "команда linux посмотреть место на диске", "как посмотреть место на диске", "как проверить свободное место", "проверить свободное место", "проверить место на диске", "проверить место на диске linux", "disk space linux"], "linux", "Показывает использование файловых систем в удобных для чтения единицах.", ["Смотрите столбцы Size, Used, Avail и Use%.", "df показывает файловые системы, а du помогает найти крупные каталоги."], ["df -h", "du -sh /var/* | sort -h"], ["disk", "filesystem", "du"]),
  card("linux-free", "free -h", ["free -h command", "команда free -h", "память linux", "linux memory usage"], "linux", "Показывает использование оперативной памяти и swap в Linux.", ["Поле available обычно полезнее, чем просто free.", "Linux использует свободную память под кеш и освобождает ее при необходимости."], ["free -h", "watch -n 2 free -h"], ["memory", "swap", "linux"]),

  card("docker-image", "Docker image", ["docker image", "образ docker", "docker образ", "что такое docker image"], "docker", "Неизменяемый шаблон с приложением, зависимостями и метаданными для запуска контейнеров.", ["Image строится слоями.", "Один image может запускать много контейнеров.", "Обычно хранится в registry."], ["docker image ls", "docker inspect IMAGE"], ["docker-container", "dockerfile", "registry"]),
  card("docker-container", "Docker container", ["docker container", "контейнер docker", "docker контейнер", "что такое контейнер"], "docker", "Запущенный или остановленный экземпляр Docker image с изолированными процессами и файловой системой.", ["Контейнер не является полноценной виртуальной машиной.", "Изменяемые данные лучше хранить в volume."], ["docker ps -a", "docker inspect CONTAINER"], ["docker-image", "docker-run", "volume"]),
  card("dockerfile", "Dockerfile", ["dockerfile", "docker file", "докерфайл", "что такое dockerfile"], "docker", "Текстовый рецепт сборки Docker image из последовательности инструкций.", ["FROM задает базовый image.", "COPY и RUN формируют слои.", "CMD или ENTRYPOINT задают запуск контейнера."], ["docker build -t my-app ."], ["docker-image", "docker-build"]),
  card("docker-build", "docker build", ["docker build", "собрать docker image", "сборка docker образа"], "docker", "Собирает Docker image по Dockerfile и build context.", ["Контекст обычно указывается последним аргументом.", "Тег -t делает image удобным для запуска и публикации."], ["docker build -t my-app:latest .", "docker build --no-cache -t my-app ."], ["dockerfile", "docker-image"]),
  card("docker-run", "docker run", ["docker run", "запустить docker контейнер", "run container"], "docker", "Создает контейнер из image и запускает его.", ["-d запускает в фоне.", "-p публикует порт, -v подключает volume, --rm удаляет контейнер после остановки."], ["docker run --rm -p 8080:80 nginx", "docker run -d --name app my-app"], ["docker-container", "docker-image"]),
  card("docker-ps", "docker ps", ["docker ps", "список docker контейнеров", "list docker containers"], "docker", "Показывает запущенные контейнеры и их состояние.", ["Без ключей видны только запущенные контейнеры.", "-a добавляет остановленные контейнеры."], ["docker ps", "docker ps -a", "docker ps --format \"table {{.Names}}\\t{{.Status}}\\t{{.Ports}}\""], ["docker-container", "docker-logs"]),
  card("docker-logs", "docker logs", ["docker logs", "логи docker контейнера", "логи контейнера", "container logs", "как посмотреть логи docker", "показать логи docker"], "docker", "Показывает stdout и stderr выбранного контейнера.", ["-f продолжает следить за новыми строками.", "--since ограничивает временной диапазон."], ["docker logs CONTAINER", "docker logs -f --tail 100 CONTAINER"], ["docker-container", "journalctl"]),

  card("kubernetes-pod", "Kubernetes pod", ["kubernetes pod", "k8s pod", "под kubernetes", "что такое pod", "что такое под в kubernetes"], "kubernetes", "Минимальная единица запуска в Kubernetes: один или несколько контейнеров с общей сетью и томами.", ["Pod обычно создается контроллером, а не вручную.", "Контейнеры внутри Pod используют один IP и могут обращаться через localhost.", "Pod считается временным объектом."], ["kubectl get pods", "kubectl describe pod POD"], ["deployment", "container", "service"]),
  card("kubernetes-deployment", "Kubernetes deployment", ["kubernetes deployment", "k8s deployment", "деплоймент kubernetes", "что такое deployment"], "kubernetes", "Контроллер, который поддерживает нужное число реплик Pod и выполняет обновления приложения.", ["Управляет ReplicaSet.", "Поддерживает rolling update и rollback.", "Желаемое состояние хранится в manifest."], ["kubectl get deployments", "kubectl rollout status deployment/APP", "kubectl rollout undo deployment/APP"], ["pod", "replicaset", "kubectl"]),
  card("kubernetes-service", "Kubernetes service", ["kubernetes service", "k8s service", "сервис kubernetes", "что такое service kubernetes"], "kubernetes", "Стабильная виртуальная точка доступа к группе Pod, выбранных selector-ом.", ["Service отделяет клиентов от временных IP Pod.", "Частые типы: ClusterIP, NodePort и LoadBalancer."], ["kubectl get services", "kubectl describe service SERVICE"], ["pod", "ingress", "dns"]),
  card("kubernetes-ingress", "Kubernetes ingress", ["kubernetes ingress", "k8s ingress", "ингресс kubernetes", "что такое ingress", "ingress"], "kubernetes", "Правила HTTP/HTTPS-маршрутизации внешнего трафика к Kubernetes Service.", ["Для работы нужен Ingress Controller.", "Обычно маршрутизирует по hostname и URL path.", "TLS настраивается через Secret и правила ingress."], ["kubectl get ingress", "kubectl describe ingress INGRESS"], ["service", "load balancer", "dns"]),
  card("kubectl-get-pods", "kubectl get pods", ["kubectl get pods", "список pod kubernetes", "показать поды", "list kubernetes pods"], "kubernetes", "Показывает Pod, их готовность, статус, перезапуски и возраст.", ["-A показывает все namespaces.", "-o wide добавляет node, IP и другие детали."], ["kubectl get pods", "kubectl get pods -A -o wide"], ["pod", "kubectl-describe", "kubectl-logs"]),
  card("kubectl-describe", "kubectl describe", ["kubectl describe", "описание ресурса kubernetes", "describe pod"], "kubernetes", "Показывает подробное состояние ресурса и связанные события Kubernetes.", ["Особенно полезно при Pending, CrashLoopBackOff и ошибках scheduling.", "События внизу часто объясняют причину проблемы."], ["kubectl describe pod POD", "kubectl describe deployment APP"], ["kubectl-get-pods", "events"]),
  card("kubectl-logs", "kubectl logs", ["kubectl logs", "логи pod kubernetes", "логи kubernetes", "pod logs", "как посмотреть логи pod", "как посмотреть логи kubernetes"], "kubernetes", "Читает stdout и stderr контейнера внутри Pod.", ["Для нескольких контейнеров укажите -c.", "--previous показывает логи предыдущего упавшего контейнера."], ["kubectl logs POD", "kubectl logs -f POD -c CONTAINER", "kubectl logs POD --previous"], ["pod", "kubectl-describe", "logs"]),
  card("kubernetes-basic-commands", "Основные команды Kubernetes и kubectl", ["основные команды kubernetes", "перечислите основные команды kubernetes", "перечисли основные команды kubernetes", "какие основные команды kubernetes", "какие основные команды вы знаете kubernetes", "какие команды вы знаете kubernetes", "команды kubectl", "основные команды kubectl", "покажи команды kubernetes", "kubernetes basic commands", "kubectl basic commands"], "kubernetes", "Короткий набор kubectl-команд для просмотра ресурсов, диагностики и применения конфигурации.", ["Перед изменениями проверьте текущий context и namespace.", "Для диагностики обычно начинают с get, затем describe и logs.", "apply изменяет состояние кластера, поэтому сначала проверьте manifest и выбранный context."], ["kubectl config current-context", "kubectl get pods -A", "kubectl get svc -A", "kubectl describe pod POD -n NAMESPACE", "kubectl logs POD -n NAMESPACE", "kubectl apply -f manifest.yaml"], ["kubectl", "pod", "service", "namespace", "context"]),

  card("network-nat", "NAT", ["nat", "network address translation", "что такое nat", "трансляция сетевых адресов"], "networking", "Преобразует IP-адреса и иногда порты между сетями, часто между частной сетью и интернетом.", ["SNAT меняет адрес источника.", "DNAT меняет адрес назначения.", "PAT позволяет многим устройствам делить один внешний IP через разные порты."], ["iptables -t nat -L -n -v", "Get-NetNat"], ["port", "routing", "firewall"]),
  card("network-dns", "DNS", ["dns", "domain name system", "что такое dns", "как работает dns", "система доменных имен"], "networking", "Преобразует доменные имена в IP-адреса и хранит другие записи о доменах.", ["Клиент обычно обращается к recursive resolver.", "A/AAAA указывают адрес, CNAME — псевдоним, MX — почтовый сервер.", "Кеш и TTL влияют на скорость распространения изменений."], ["nslookup example.com", "dig example.com A"], ["nslookup", "active-directory-dns", "dhcp"]),
  card("network-dhcp", "DHCP", ["dhcp", "dynamic host configuration protocol", "что такое dhcp", "как работает dhcp"], "networking", "Автоматически выдает клиентам IP-настройки: адрес, маску, gateway, DNS и срок аренды.", ["Классическая последовательность: Discover, Offer, Request, Acknowledge.", "Reservation закрепляет адрес за конкретным клиентом."], ["ipconfig /all", "ipconfig /renew", "nmcli device show"], ["dns", "ip address", "dhcp-role"]),
  card("network-ping", "ping", ["ping command", "команда ping", "проверить доступность хоста", "icmp ping"], "networking", "Проверяет сетевую достижимость и приблизительную задержку с помощью ICMP Echo.", ["Успешный ping не гарантирует работу нужного TCP-порта.", "ICMP может быть заблокирован firewall, даже если сервис доступен."], ["ping 8.8.8.8", "ping example.com"], ["traceroute", "dns", "port"]),
  card("network-traceroute", "traceroute / tracert", ["traceroute", "tracert", "trace route", "трассировка маршрута", "как проверить маршрут"], "networking", "Показывает последовательность сетевых узлов до назначения и помогает искать участок задержки или потерь.", ["В Linux обычно используется traceroute или tracepath.", "В Windows используется tracert.", "Некоторые промежуточные узлы не отвечают на диагностические пакеты."], ["traceroute example.com", "tracert example.com"], ["ping", "routing"]),
  card("network-dns-tools", "nslookup / dig", ["nslookup", "dig command", "команда dig", "проверить dns", "dns lookup"], "networking", "Диагностические утилиты для запроса DNS-записей и проверки resolver-ов.", ["nslookup доступен на Windows и многих Unix-системах.", "dig дает более подробный и скриптуемый ответ."], ["nslookup example.com", "nslookup example.com 8.8.8.8", "dig example.com +short"], ["dns", "active-directory-dns"]),

  card("active-directory", "Active Directory", ["active directory", "актив директори", "что такое active directory", "ad domain"], "active-directory", "Каталог Microsoft для централизованного управления пользователями, компьютерами, группами и политиками домена.", ["Основной протокол каталога — LDAP, аутентификация обычно использует Kerberos.", "Структура включает forest, domain и organizational units.", "AD сильно зависит от корректного DNS."], ["Get-ADDomain", "Get-ADUser -Filter *"], ["domain-controller", "group-policy", "active-directory-dns"]),
  card("domain-controller", "Domain Controller", ["domain controller", "контроллер домена", "что такое domain controller", "dc active directory"], "active-directory", "Сервер с ролью AD DS, который аутентифицирует пользователей и хранит реплицируемую копию каталога.", ["Обычно также участвует в DNS домена.", "Несколько DC повышают отказоустойчивость.", "FSMO-роли распределяют отдельные обязанности."], ["Get-ADDomainController -Filter *", "dcdiag"], ["active-directory", "active-directory-dns", "kerberos"]),
  card("group-policy", "Group Policy", ["group policy", "групповая политика", "gpo", "что такое group policy"], "active-directory", "Механизм централизованной настройки пользователей и компьютеров Windows в домене.", ["Настройки хранятся в GPO и связываются с site, domain или OU.", "Порядок и наследование влияют на итоговую политику."], ["gpupdate /force", "gpresult /r", "Get-GPO -All"], ["active-directory", "organizational unit"]),
  card("active-directory-dns", "DNS в Active Directory", ["dns in ad", "dns в active directory", "ad dns", "dns active directory"], "active-directory", "DNS помогает клиентам находить контроллеры домена и службы AD через специальные SRV-записи.", ["Клиенты домена должны использовать DNS, знающий зону AD.", "Ошибочный внешний DNS часто ломает domain join и вход.", "AD-integrated зоны могут реплицироваться через каталог."], ["nslookup -type=SRV _ldap._tcp.dc._msdcs.DOMAIN", "dcdiag /test:dns"], ["active-directory", "domain-controller", "dns"]),
  card("dhcp-role", "DHCP role", ["dhcp role", "роль dhcp", "dhcp server windows", "dhcp в windows server"], "active-directory", "Серверная роль, которая централизованно выдает IP-конфигурацию клиентам сети.", ["Scope определяет пул адресов и параметры сети.", "В доменной среде DHCP-сервер обычно авторизуют в AD.", "Failover помогает обеспечить доступность выдачи адресов."], ["Get-DhcpServerv4Scope", "Get-DhcpServerInDC"], ["dhcp", "active-directory", "dns"])
];

const practicalKnowledgeCards: KnowledgeCard[] = [
  card("linux-systemctl-status", "Проверка статуса сервиса через systemctl", ["systemctl status", "как проверить статус сервиса", "проверить статус службы linux", "check service status", "service status linux"], "linux", "Показывает, запущен ли systemd-сервис, его PID, последние события и причину сбоя.", ["Используйте точное имя unit, обычно с суффиксом .service.", "Строки Active и Loaded дают быстрый ответ о состоянии и автозапуске."], ["systemctl status nginx", "systemctl is-active nginx", "systemctl is-enabled nginx"], ["systemctl", "journalctl", "systemd"]),
  card("linux-systemctl-restart", "Перезапуск сервиса через systemctl", ["systemctl restart", "как перезапустить сервис", "перезапустить службу linux", "restart service linux", "restart systemd service"], "linux", "Останавливает и снова запускает systemd-сервис, например после изменения конфигурации.", ["Сначала по возможности проверьте конфигурацию приложения.", "После рестарта проверьте status и журнал сервиса."], ["sudo systemctl restart nginx", "systemctl status nginx --no-pager"], ["systemctl", "journalctl", "service status"]),
  card("linux-journalctl-service", "Просмотр логов сервиса через journalctl", ["journalctl -u", "как посмотреть логи сервиса", "посмотреть логи службы", "логи сервиса linux", "view service logs", "service logs journalctl"], "linux", "Фильтрует системный журнал по конкретному systemd unit.", ["--since ограничивает период и уменьшает шум.", "-n показывает заданное число последних строк."], ["journalctl -u nginx --since today", "journalctl -u nginx -n 100 --no-pager"], ["journalctl", "systemctl", "logs"]),
  card("linux-journalctl-follow", "Просмотр логов в реальном времени: journalctl -f", ["journalctl -f", "следить за логами сервиса", "логи в реальном времени linux", "follow service logs", "tail systemd logs"], "linux", "Показывает новые записи журнала по мере их появления.", ["Добавьте -u UNIT, чтобы следить только за нужным сервисом.", "Остановите просмотр сочетанием Ctrl+C."], ["journalctl -f", "journalctl -fu nginx"], ["journalctl", "service logs", "systemd"]),
  card("linux-find-large-files", "Поиск больших файлов в Linux", ["найти большие файлы", "как найти большие файлы linux", "find large files", "largest files linux", "du sort files"], "linux", "Помогает быстро найти файлы и каталоги, которые занимают много дискового пространства.", ["du удобен для каталогов, find — для отдельных файлов.", "Запускайте поиск с нужной точки, чтобы не сканировать всю систему без необходимости."], ["sudo du -ah /var | sort -h | tail -20", "sudo find /var -type f -size +500M -printf '%s %p\\n' | sort -n"], ["df -h", "du", "filesystem"]),
  card("linux-processes", "Проверка CPU и процессов: top, htop, ps", ["top command", "htop command", "ps aux", "проверить процессы linux", "нагрузка cpu linux", "check cpu processes", "process list linux"], "linux", "Показывает процессы, загрузку CPU, память и состояние системы.", ["top доступен почти всегда, htop удобнее интерактивно.", "ps полезен для разового фильтруемого снимка."], ["top", "htop", "ps aux --sort=-%cpu | head"], ["process", "cpu", "free -h"]),
  card("linux-kill-process", "Завершение процесса в Linux", ["kill process", "kill command", "как завершить процесс linux", "убить процесс linux", "terminate process linux"], "linux", "Отправляет процессу сигнал завершения по PID или имени.", ["Начинайте с обычного SIGTERM, чтобы процесс завершился корректно.", "SIGKILL (-9) используйте только если процесс не реагирует."], ["kill PID", "pkill PROCESS_NAME", "kill -9 PID"], ["ps", "top", "process"]),
  card("linux-ip-addr", "Проверка IP-адресов: ip addr", ["ip addr", "ip address linux", "как проверить ip адрес linux", "показать ip linux", "check ip address linux"], "linux", "Показывает сетевые интерфейсы, назначенные IPv4/IPv6-адреса и состояние link.", ["Краткий вывод удобнее смотреть с ключом -br.", "Адрес 127.0.0.1 относится к loopback, а не к внешнему интерфейсу."], ["ip addr", "ip -br addr"], ["ip route", "interface", "networking"]),
  card("linux-ip-route", "Проверка маршрутов: ip route", ["ip route", "route table linux", "как проверить маршруты linux", "таблица маршрутизации linux", "check routes linux"], "linux", "Показывает таблицу маршрутизации и default gateway Linux.", ["Маршрут default используется, когда более точного маршрута нет.", "Команда route устарела; обычно применяют ip route."], ["ip route", "ip route get 8.8.8.8"], ["ip addr", "gateway", "traceroute"]),
  card("linux-ls-permissions", "Проверка прав доступа: ls -l", ["ls -l", "проверить права файла linux", "посмотреть permissions linux", "check file permissions", "linux permissions"], "linux", "Показывает тип объекта, права владельца, группы и остальных пользователей.", ["Первые символы выглядят как -rwxr-xr--.", "Дальше указаны владелец и группа объекта."], ["ls -l FILE", "namei -l /path/to/file"], ["chmod", "chown", "permissions"]),
  card("linux-chmod", "Изменение прав доступа: chmod", ["chmod", "chmod command", "chmod +x", "команда linux задать права на исполнение", "права на исполнение файла", "права на исполнение файла командной строки", "как сделать файл исполняемым", "как выдать права на файл", "изменить права linux", "change permissions linux", "chmod 755"], "linux", "Меняет права чтения, записи и выполнения для владельца, группы и остальных.", ["Числа 7, 5 и 4 соответствуют комбинациям rwx, r-x и r--.", "Не назначайте 777 без явной необходимости: это дает запись всем пользователям."], ["chmod +x SCRIPT", "chmod 644 FILE", "chmod 755 SCRIPT", "chmod u+x SCRIPT"], ["ls -l", "chown", "permissions"]),
  card("linux-chown", "Изменение владельца: chown", ["chown", "chown command", "изменить владельца файла", "change file owner linux", "change ownership linux"], "linux", "Меняет владельца и группу файла или каталога.", ["Ключ -R применяет изменение рекурсивно и требует осторожности: неверный owner может сломать сервис или открыть доступ.", "После изменения проверьте результат через ls -l."], ["sudo chown USER:GROUP FILE", "sudo chown -R USER:GROUP DIRECTORY"], ["ls -l", "chmod", "ownership"]),
  card("linux-mount", "Подключение дисков: mount", ["mount disk linux", "команда mount", "как смонтировать диск", "подключить диск linux", "mount filesystem"], "linux", "Подключает файловую систему устройства к каталогу в дереве Linux.", ["Перед mount создайте точку монтирования.", "Для постоянного подключения добавляют запись в /etc/fstab."], ["lsblk -f", "sudo mount /dev/sdb1 /mnt/data", "mount | grep /mnt/data"], ["fstab", "lsblk", "filesystem"]),
  card("linux-fstab", "Проверка /etc/fstab", ["fstab", "/etc/fstab", "проверить fstab", "настроить автомонтирование linux", "check fstab", "persistent mount linux"], "linux", "Файл /etc/fstab описывает файловые системы, которые должны монтироваться автоматически.", ["Предпочтительно использовать UUID вместо /dev/sdX.", "Проверяйте конфигурацию командой mount -a до перезагрузки."], ["cat /etc/fstab", "lsblk -f", "sudo mount -a"], ["mount", "uuid", "filesystem"]),

  card("docker-images", "Список Docker images", ["docker images", "docker image ls", "список docker образов", "показать docker images", "list docker images"], "docker", "Показывает локальные Docker images, их теги, ID, дату и размер.", ["Dangling images не имеют тега и часто остаются после сборок.", "Удаляйте image только когда он не нужен контейнерам."], ["docker images", "docker image ls", "docker image prune"], ["docker image", "docker build", "registry"]),
  card("docker-exec", "Выполнение команды в контейнере: docker exec", ["docker exec", "как зайти в контейнер", "зайти в контейнер", "зайти в docker контейнер", "выполнить команду в контейнере", "shell in container", "execute in docker container"], "docker", "Запускает новый процесс внутри уже работающего контейнера.", ["-it нужен для интерактивного терминала.", "В минимальных images может быть sh, но не bash."], ["docker exec -it CONTAINER sh", "docker exec CONTAINER env"], ["docker container", "docker ps", "shell"]),
  card("docker-inspect", "Подробности объекта: docker inspect", ["docker inspect", "посмотреть настройки контейнера", "inspect docker container", "docker container details"], "docker", "Возвращает подробную JSON-конфигурацию контейнера, image, volume или network.", ["Полезен для IP, mounts, environment и restart policy.", "--format позволяет извлечь одно поле."], ["docker inspect CONTAINER", "docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' CONTAINER"], ["docker container", "docker network", "docker volume"]),
  card("docker-compose-up", "Запуск Compose-проекта: docker compose up", ["docker compose up", "запустить docker compose", "compose up", "start compose project"], "docker", "Создает и запускает сервисы, сети и volumes из compose.yaml.", ["-d запускает проект в фоне.", "--build пересобирает images перед запуском."], ["docker compose up -d", "docker compose up -d --build"], ["docker compose down", "compose", "docker service"]),
  card("docker-compose-down", "Остановка Compose-проекта: docker compose down", ["docker compose down", "остановить docker compose", "compose down", "stop compose project"], "docker", "Останавливает и удаляет контейнеры и сети текущего Compose-проекта.", ["Volumes по умолчанию сохраняются.", "Ключ -v удаляет named volumes и данные в них."], ["docker compose down", "docker compose down -v"], ["docker compose up", "compose", "docker volume"]),
  card("docker-compose-logs", "Логи Compose-сервисов: docker compose logs", ["docker compose logs", "логи docker compose", "посмотреть логи compose", "compose service logs", "follow compose logs"], "docker", "Собирает stdout и stderr сервисов Compose-проекта.", ["Укажите имя сервиса, чтобы сократить вывод.", "-f продолжает показывать новые строки."], ["docker compose logs", "docker compose logs -f --tail 100 SERVICE"], ["docker logs", "docker compose up", "logs"]),
  card("docker-volumes", "Docker volumes", ["docker volumes", "docker volume", "тома docker", "что такое docker volume", "list docker volumes"], "docker", "Хранят данные контейнеров отдельно от их изменяемого слоя.", ["Named volume переживает пересоздание контейнера.", "Перед удалением проверьте, что данные больше не нужны."], ["docker volume ls", "docker volume inspect VOLUME", "docker volume prune"], ["docker container", "mount", "persistent data"]),
  card("docker-networks", "Docker networks", ["docker networks", "docker network", "сети docker", "что такое docker network", "list docker networks"], "docker", "Соединяют контейнеры и обеспечивают DNS по именам контейнеров или сервисов.", ["Пользовательская bridge-сеть удобнее стандартной для связи контейнеров.", "inspect показывает подключенные контейнеры и подсети."], ["docker network ls", "docker network inspect NETWORK", "docker network create app-net"], ["docker container", "dns", "bridge"]),

  card("kubectl-get-svc", "Просмотр Kubernetes Service: kubectl get svc", ["kubectl get svc", "kubectl get services", "показать сервисы kubernetes", "list kubernetes services"], "kubernetes", "Показывает Service, их ClusterIP, внешние адреса и опубликованные порты.", ["-A выводит сервисы всех namespaces.", "EXTERNAL-IP может оставаться pending без поддерживаемого LoadBalancer."], ["kubectl get svc", "kubectl get svc -A -o wide"], ["kubernetes service", "namespace", "ingress"]),
  card("kubectl-exec", "Выполнение команды в Pod: kubectl exec", ["kubectl exec", "зайти в pod", "выполнить команду в pod", "shell in kubernetes pod", "execute in pod"], "kubernetes", "Запускает команду внутри контейнера работающего Pod.", ["Для нескольких контейнеров укажите -c.", "Разделитель -- отделяет параметры kubectl от команды контейнера."], ["kubectl exec -it POD -- sh", "kubectl exec POD -c CONTAINER -- env"], ["pod", "kubectl logs", "container"]),
  card("kubectl-apply", "Применение manifest: kubectl apply", ["kubectl apply", "применить manifest kubernetes", "apply yaml kubernetes", "deploy kubernetes yaml"], "kubernetes", "Создает или обновляет Kubernetes-ресурсы декларативно из YAML-файла.", ["Сначала можно выполнить server-side dry-run.", "Храните manifests в системе контроля версий."], ["kubectl apply -f manifest.yaml", "kubectl apply -f manifest.yaml --dry-run=server"], ["manifest", "kubectl delete", "deployment"]),
  card("kubectl-delete", "Удаление ресурса: kubectl delete", ["kubectl delete", "удалить ресурс kubernetes", "delete kubernetes resource", "remove kubernetes pod"], "kubernetes", "Удаляет выбранный Kubernetes-ресурс по имени или manifest-файлу.", ["Контроллер может немедленно пересоздать удаленный Pod.", "Всегда проверяйте namespace перед удалением."], ["kubectl delete pod POD", "kubectl delete -f manifest.yaml"], ["kubectl apply", "namespace", "controller"]),
  card("kubectl-rollout-restart", "Перезапуск Deployment: kubectl rollout restart", ["kubectl rollout restart", "перезапустить deployment", "как перезапустить kubernetes", "как перезапустить deployment kubernetes", "как перезапустить pod kubernetes", "например как перезапустить kubernetes", "restart kubernetes deployment", "restart pods deployment"], "kubernetes", "Запускает новый rollout Deployment без изменения image.", ["Pod заменяются постепенно согласно стратегии Deployment.", "После запуска проверьте rollout status."], ["kubectl rollout restart deployment/APP", "kubectl rollout restart deployment/APP -n NAMESPACE"], ["deployment", "kubectl rollout status", "pod"]),
  card("kubectl-rollout-status", "Статус обновления: kubectl rollout status", ["kubectl rollout status", "проверить rollout kubernetes", "статус deployment kubernetes", "check rollout status"], "kubernetes", "Ожидает завершения rollout и сообщает об успешном обновлении или проблеме.", ["При зависании проверьте Pod и события Deployment.", "Команда подходит для CI/CD после apply."], ["kubectl rollout status deployment/APP", "kubectl rollout history deployment/APP"], ["deployment", "kubectl rollout restart", "kubectl describe"]),
  card("kubectl-port-forward", "Локальный доступ: kubectl port-forward", ["kubectl port-forward", "проброс порта kubernetes", "доступ к pod локально", "forward kubernetes port"], "kubernetes", "Проксирует локальный TCP-порт к Pod или Service для диагностики.", ["Соединение работает, пока запущена команда.", "Это инструмент диагностики, а не постоянная публикация сервиса."], ["kubectl port-forward pod/POD 8080:80", "kubectl port-forward service/SERVICE 8080:80"], ["pod", "service", "port"]),
  card("kubernetes-namespace", "Namespaces в Kubernetes", ["kubernetes namespace", "kubectl namespace", "пространство имен kubernetes", "namespace basics", "switch namespace"], "kubernetes", "Логически разделяют ресурсы одного кластера между командами или окружениями.", ["Большинство kubectl-команд принимают -n NAMESPACE.", "Текущий namespace можно сохранить в context."], ["kubectl get namespaces", "kubectl get pods -n NAMESPACE", "kubectl config set-context --current --namespace=NAMESPACE"], ["context", "kubectl", "cluster"]),
  card("kubernetes-context", "Contexts в kubectl", ["kubectl context", "kubernetes context", "сменить контекст kubectl", "context basics", "switch kubernetes cluster"], "kubernetes", "Context объединяет кластер, пользователя и namespace для команд kubectl.", ["Перед изменениями всегда проверяйте текущий context.", "Ошибка context может направить команду в другой кластер."], ["kubectl config current-context", "kubectl config get-contexts", "kubectl config use-context CONTEXT"], ["namespace", "kubeconfig", "cluster"]),

  card("network-nslookup", "Проверка DNS через nslookup", ["nslookup", "nslookup command", "команда nslookup", "проверить dns запись windows", "dns lookup windows"], "networking", "Запрашивает DNS-имя или запись у системного либо указанного DNS-сервера.", ["Можно явно указать сервер вторым аргументом.", "Для подробной диагностики в Linux часто удобнее dig."], ["nslookup example.com", "nslookup example.com 8.8.8.8", "nslookup -type=MX example.com"], ["dig", "dns", "dns records"]),
  card("network-dig", "Проверка DNS через dig", ["dig", "dig command", "команда dig", "проверить dns linux", "dns lookup linux"], "networking", "Показывает подробный DNS-ответ, сервер, секции и время запроса.", ["+short оставляет только краткий результат.", "Укажите @SERVER для запроса конкретного resolver."], ["dig example.com A", "dig @8.8.8.8 example.com +short", "dig example.com MX"], ["nslookup", "dns", "dns records"]),
  card("network-curl", "HTTP-проверка через curl", ["curl", "curl command", "команда curl", "проверить http endpoint", "http request command"], "networking", "Отправляет HTTP-запросы и помогает проверить доступность, заголовки и ответы API.", ["-I запрашивает только заголовки.", "-v показывает детали DNS, TLS и соединения."], ["curl -I https://example.com", "curl -v http://HOST:PORT/health", "curl -sS https://example.com/api"], ["http", "tls", "port"]),
  card("network-netcat", "Проверка TCP/UDP через nc (netcat)", ["nc command", "netcat", "nc -vz", "проверить порт nc", "test port netcat"], "networking", "Проверяет, устанавливается ли TCP-соединение с нужным хостом и портом.", ["-z выполняет проверку без передачи данных.", "Успех показывает доступность порта, но не корректность приложения."], ["nc -vz HOST 443", "nc -vzu HOST 53"], ["port", "telnet", "curl"]),
  card("network-telnet-port", "Проверка порта через telnet", ["telnet port test", "проверить порт telnet", "telnet host port", "test tcp port telnet"], "networking", "Открывает простое TCP-соединение и может подтвердить достижимость порта.", ["Telnet-клиент может быть не установлен.", "Для автоматизации и таймаутов обычно удобнее nc или Test-NetConnection."], ["telnet HOST 443", "Test-NetConnection HOST -Port 443"], ["nc", "port", "tcp"]),
  card("network-dns-records", "Типы DNS-записей: A, CNAME, MX, TXT", ["dns record types", "типы dns записей", "a cname mx txt", "dns a record", "dns cname mx txt"], "networking", "DNS-записи описывают адреса, псевдонимы, почтовые серверы и текстовые данные домена.", ["A связывает имя с IPv4, CNAME — с другим именем.", "MX задает почтовые серверы, TXT часто хранит SPF и подтверждения владения."], ["dig example.com A", "dig example.com CNAME", "dig example.com MX", "dig example.com TXT"], ["dns", "nslookup", "dig"]),
  card("network-dhcp-lease", "Аренда адреса DHCP", ["dhcp lease", "аренда dhcp", "срок аренды ip", "renew dhcp lease", "dhcp lease basics"], "networking", "DHCP lease временно закрепляет IP-конфигурацию за клиентом.", ["Клиент пытается продлить lease до истечения срока.", "Reservation связывает постоянный адрес с MAC или client identifier."], ["ipconfig /all", "ipconfig /release && ipconfig /renew", "nmcli device show"], ["dhcp", "ip address", "reservation"]),

  card("ad-check-domain-controller", "Проверка контроллеров домена", ["проверить контроллер домена", "check domain controller", "list domain controllers", "get addomaincontroller"], "active-directory", "Показывает доступные Domain Controller и помогает проверить, какой DC обслуживает клиент.", ["Проверяйте DNS, site и доступность нужного DC.", "Переменная LOGONSERVER показывает DC текущего входа."], ["echo %LOGONSERVER%", "nltest /dsgetdc:DOMAIN", "Get-ADDomainController -Filter *"], ["domain controller", "dns in ad", "dcdiag"]),
  card("ad-dns-records", "Проверка DNS-записей Active Directory", ["проверить dns записи ad", "check ad dns records", "ad srv records", "dns records active directory"], "active-directory", "Проверяет SRV-записи, по которым клиенты находят LDAP, Kerberos и контроллеры домена.", ["Клиент домена должен использовать внутренний DNS AD.", "Отсутствующие SRV-записи часто указывают на проблемы DNS или Netlogon."], ["nslookup -type=SRV _ldap._tcp.dc._msdcs.DOMAIN", "Resolve-DnsName -Type SRV _kerberos._tcp.DOMAIN", "dcdiag /test:dns"], ["dns in ad", "domain controller", "dcdiag"]),
  card("ad-gpupdate", "Обновление групповых политик: gpupdate", ["gpupdate", "gpupdate force", "обновить групповые политики", "refresh group policy"], "active-directory", "Принудительно обновляет пользовательские и компьютерные Group Policy на Windows-клиенте.", ["/force повторно применяет все параметры.", "Некоторые политики требуют выхода пользователя или перезагрузки."], ["gpupdate /force", "gpupdate /target:computer /force"], ["group policy", "gpresult", "gpo"]),
  card("ad-gpresult", "Проверка примененных политик: gpresult", ["gpresult", "gpresult command", "какие gpo применились", "check applied group policy", "resultant set of policy"], "active-directory", "Показывает примененные GPO и итоговые параметры для пользователя или компьютера.", ["/r дает краткий отчет.", "/h создает удобный HTML-отчет для анализа."], ["gpresult /r", "gpresult /h C:\\Temp\\gpresult.html"], ["group policy", "gpupdate", "gpo"]),
  card("ad-dcdiag", "Диагностика контроллера домена: dcdiag", ["dcdiag", "dcdiag command", "dcdiag проверить контроллер домена", "диагностика контроллера домена", "test domain controller health"], "active-directory", "Запускает набор проверок состояния AD DS, DNS, репликации и служб Domain Controller.", ["Запускайте от администратора на DC или с подходящими RSAT.", "Ошибку лучше проверять вместе с Event Viewer и repadmin."], ["dcdiag", "dcdiag /v", "dcdiag /test:dns"], ["domain controller", "repadmin", "dns in ad"]),
  card("ad-repadmin", "Проверка репликации AD: repadmin", ["repadmin", "repadmin command", "проверить репликацию ad", "active directory replication status"], "active-directory", "Показывает состояние репликации между контроллерами домена и последние ошибки.", ["/replsummary дает сводку по всем DC.", "/showrepl показывает входящие партнеры выбранного DC."], ["repadmin /replsummary", "repadmin /showrepl", "repadmin /syncall /AdeP"], ["domain controller", "dcdiag", "replication"]),
  card("ad-fsmo", "Проверка FSMO-ролей", ["fsmo roles", "как проверить fsmo", "проверить fsmo", "проверить fsmo роли", "check fsmo roles", "netdom query fsmo"], "active-directory", "Показывает, какие Domain Controller владеют пятью специальными FSMO-ролями леса и домена.", ["Роли включают Schema Master, Domain Naming Master, RID, PDC Emulator и Infrastructure Master.", "Знать владельцев важно при обслуживании или отказе DC."], ["netdom query fsmo", "Get-ADForest | Select SchemaMaster,DomainNamingMaster", "Get-ADDomain | Select RIDMaster,PDCEmulator,InfrastructureMaster"], ["domain controller", "active directory", "replication"]),
  card("ad-gpo-basics", "Основы GPO", ["gpo basics", "основы gpo", "как работает групповая политика", "group policy basics"], "active-directory", "GPO централизованно применяет настройки к пользователям и компьютерам в site, domain и OU.", ["Порядок обработки обычно LSDOU: Local, Site, Domain, OU.", "Security filtering и WMI filters ограничивают область применения."], ["Get-GPO -All", "gpresult /h C:\\Temp\\gpresult.html", "rsop.msc"], ["group policy", "gpupdate", "gpresult"])
];

export const knowledgeCards: KnowledgeCard[] = [
  ...baseKnowledgeCards,
  ...practicalKnowledgeCards,
  ...expandedKnowledgeCards
];

const ambiguousAliases = new Set([
  "pod", "под", "log", "logs", "service", "сервис", "container", "контейнер",
  "group", "группа", "port", "порт", "ss", "free"
]);
const intentMarkers = [
  "что такое", "как работает", "для чего", "как проверить", "как настроить", "как посмотреть",
  "как добавить", "как выдать", "как дать", "как найти", "не работает", "не запускается", "не стартует", "ошибка", "команда", "command",
  "explain", "check", "show", "list", "troubleshoot"
];
const contextMarkers = [
  "linux", "systemd", "docker", "compose", "kubernetes", "k8s", "kubectl", "proxmox", "pve",
  "active directory", " ad ", "windows", "powershell", "dns", "dhcp", "tcp", "udp", "firewall",
  "network", "сеть", "memory", "память"
];

export function findKnowledgeCards(text: string): KnowledgeCard[] {
  const normalizedText = normalize(text);
  if (!normalizedText) return [];

  return knowledgeCards
    .map((knowledgeCard, index) => ({ knowledgeCard, index, score: scoreCard(knowledgeCard, normalizedText) }))
    .filter((result) => result.score > 0)
    .sort((left, right) => right.score - left.score || left.index - right.index)
    .slice(0, 2)
    .map((result) => result.knowledgeCard);
}

function scoreCard(knowledgeCard: KnowledgeCard, text: string): number {
  const candidates = [knowledgeCard.title, ...knowledgeCard.aliases].map(normalize);
  let score = 0;

  for (const candidate of candidates) {
    if (!candidate || !containsPhrase(text, candidate)) continue;
    if (ambiguousAliases.has(candidate) && !hasTechnicalContext(text, candidate)) continue;

    const exactBonus = text === candidate ? 40 : 0;
    const titleBonus = candidate === normalize(knowledgeCard.title) && candidate.length >= 6 ? 12 : 0;
    score = Math.max(score, candidate.length + exactBonus + titleBonus);
  }

  return score;
}

function hasTechnicalContext(text: string, alias: string): boolean {
  if (intentMarkers.some((marker) => text.includes(marker))) return true;
  if (contextMarkers.some((marker) => marker !== alias && text.includes(marker))) return true;
  return text.split(" ").length >= 3;
}

function containsPhrase(text: string, phrase: string): boolean {
  return ` ${text} `.includes(` ${phrase} `);
}

function normalize(value: string): string {
  return value
    .toLowerCase()
    .replace(/ё/g, "е")
    .replace(/[?!,;:]+/g, " ")
    .replace(/\.(?=\s|$)/g, " ")
    .replace(/[^a-zа-я0-9+./-]+/gi, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function card(
  id: string,
  title: string,
  aliases: string[],
  category: KnowledgeCard["category"],
  shortExplanation: string,
  bullets: string[],
  commands: string[],
  relatedTerms: string[]
): KnowledgeCard {
  return { id, title, aliases, category, shortExplanation, bullets, commands, relatedTerms };
}
