import type { KnowledgeCard } from "./knowledgeCards.js";

const linuxCards: KnowledgeCard[] = [
  card("linux-failed-services", "Проверка упавших systemd-сервисов", ["systemctl failed", "systemctl --failed", "check failed systemd services", "проверить упавшие сервисы", "какие сервисы упали linux"], "linux", "Показывает systemd units, которые завершились с ошибкой.", ["Начните со списка failed units, затем откройте status и журнал конкретного сервиса.", "После исправления причины сбросьте старое failed-состояние."], ["systemctl --failed", "systemctl status SERVICE", "sudo systemctl reset-failed SERVICE"], ["systemctl", "journalctl", "systemd"]),
  card("linux-journalctl-xe", "Диагностика ошибок: journalctl -xe", ["journalctl -xe", "последние ошибки linux", "systemd recent errors", "как посмотреть системные ошибки linux"], "linux", "Показывает последние записи systemd journal с пояснениями и важными событиями.", ["Полезно сразу после неудачного запуска службы или системной операции.", "Для точной службы обычно лучше добавить фильтр -u."], ["sudo journalctl -xe", "sudo journalctl -xeu SERVICE"], ["journalctl", "systemctl", "logs"]),
  card("linux-boot-logs", "Проверка логов загрузки Linux", ["journalctl -b", "check boot logs", "логи загрузки linux", "как посмотреть логи загрузки", "ошибки при загрузке linux"], "linux", "Фильтрует journal по текущей или предыдущей загрузке системы.", ["-b показывает текущую загрузку, -b -1 — предыдущую.", "Добавьте -p err для ошибок высокого приоритета."], ["journalctl -b", "journalctl -b -1", "journalctl -b -p err"], ["journalctl", "boot", "systemd"]),
  card("linux-inodes", "Проверка использования inode", ["df -i", "check inode usage", "проверить inode", "закончились inode", "место есть но файл не создается"], "linux", "Показывает, не исчерпано ли количество inode при наличии свободного места в гигабайтах.", ["Большое число мелких файлов может занять все inode.", "После обнаружения найдите каталоги с наибольшим количеством файлов."], ["df -i", "find /var -xdev -type f | wc -l", "du --inodes -d 2 /var | sort -n"], ["df", "filesystem", "find"]),
  card("linux-swap", "Проверка использования swap", ["check swap usage", "проверить swap", "swap linux", "swapon --show", "как посмотреть swap"], "linux", "Показывает настроенный swap и текущую активность подкачки.", ["Небольшое использование swap само по себе не означает проблему.", "Смотрите вместе с available memory и нагрузкой ввода-вывода."], ["free -h", "swapon --show", "vmstat 1"], ["memory", "free", "vmstat"]),
  card("linux-cpu-load", "Проверка нагрузки CPU и load average", ["как посмотреть нагрузку", "проверить нагрузку linux", "check cpu load", "load average linux", "uptime load"], "linux", "Показывает load average и процессы, потребляющие CPU.", ["Load average сравнивайте с количеством CPU cores.", "Высокий load может быть вызван не только CPU, но и ожиданием I/O."], ["uptime", "top", "ps aux --sort=-%cpu | head"], ["cpu", "top", "processes"]),
  card("linux-firewall-status", "Проверка firewall в Linux", ["check firewall status linux", "проверить firewall linux", "проверить firewall", "статус firewall", "статус фаервола", "какой firewall работает", "ufw status", "firewall-cmd --state", "iptables -l"], "linux", "Помогает определить активный firewall и текущие правила фильтрации.", ["На разных системах используются firewalld, nftables, iptables или ufw.", "Проверяйте и правила, и факт прослушивания порта приложением."], ["sudo ufw status verbose", "sudo firewall-cmd --state", "sudo iptables -L -n -v", "sudo nft list ruleset"], ["firewalld", "iptables", "nftables", "port"]),
  card("linux-firewalld", "Основы firewalld", ["firewalld basics", "firewall-cmd", "настроить firewalld", "открыть порт firewalld", "проверить правила firewalld"], "linux", "firewalld управляет зонами и правилами firewall через firewall-cmd.", ["Временные правила исчезают после перезапуска.", "Для постоянного правила используйте --permanent и затем reload."], ["sudo firewall-cmd --list-all", "sudo firewall-cmd --add-port=8080/tcp --permanent", "sudo firewall-cmd --reload"], ["firewall", "port", "zones"]),
  card("linux-iptables", "Основы iptables", ["iptables basics", "iptables command", "iptables -l", "проверить iptables", "правила iptables", "открыть порт iptables"], "linux", "iptables просматривает и изменяет правила фильтрации пакетов в ядре Linux.", ["Сначала смотрите цепочки INPUT, OUTPUT и FORWARD.", "На новых системах команды могут работать через backend nftables."], ["sudo iptables -L -n -v --line-numbers", "sudo iptables -S", "sudo iptables -t nat -L -n -v"], ["firewall", "nftables", "nat"]),
  card("linux-selinux", "Проверка состояния SELinux", ["getenforce", "sestatus", "check selinux status", "проверить selinux", "selinux блокирует"], "linux", "Показывает режим SELinux и помогает выявить блокировки политики безопасности.", ["Enforcing применяет правила, Permissive только журналирует нарушения.", "Не отключайте SELinux до проверки audit log и контекста файла."], ["getenforce", "sestatus", "sudo ausearch -m AVC -ts recent"], ["security", "audit", "permissions"]),
  card("linux-users", "Проверка пользователей в Linux", ["check users linux", "посмотреть пользователей linux", "список пользователей", "who command", "кто вошел linux"], "linux", "Показывает учетные записи и активные пользовательские сессии.", ["/etc/passwd содержит локальные учетные записи.", "who и w показывают текущие входы и активность."], ["cut -d: -f1 /etc/passwd", "who", "w", "id USER"], ["users", "groups", "authentication"]),
  card("linux-sudo-permissions", "Проверка прав sudo", ["sudo -l", "check sudo permissions", "проверить права sudo", "что может sudo пользователь", "sudoers permissions"], "linux", "Показывает, какие команды пользователь может запускать через sudo.", ["sudo -l проверяет эффективные правила текущего пользователя.", "Файлы sudoers редактируйте через visudo, чтобы проверить синтаксис."], ["sudo -l", "sudo -l -U USER", "sudo visudo -c"], ["sudoers", "users", "permissions"]),
  card("linux-permissions-overview", "Права в Linux: chmod, chown и sudo", ["как дать права в linux", "как дать права в линукс", "дать права linux", "дать права линукс", "как выдать права в linux", "как выдать права в линукс", "права в linux", "права в линукс", "как дать права пользователю linux", "как дать права пользователю в linux", "как дать права пользователю в линукс", "как выдать права пользователю linux", "как выдать права пользователю в linux", "как выдать права пользователю в линукс", "linux permissions", "chmod chown sudo"], "linux", "Фраза «дать права» в Linux может означать права файла через chmod, смену владельца через chown или административный доступ через sudo и группы.", ["Для файла или каталога сначала проверьте текущие права и владельца, затем меняйте только нужный доступ.", "Для административных прав добавьте пользователя в sudo или wheel и проверьте его группы после нового входа.", "Точные правила sudoers редактируйте через visudo, чтобы не повредить конфигурацию."], ["ls -l file", "chmod +x script.sh", "chmod 755 script.sh", "chown user:group file", "usermod -aG sudo username", "usermod -aG wheel username", "groups username", "id username", "visudo"], ["chmod", "chown", "sudo", "sudoers", "file permissions", "user groups"]),
  card("linux-security-quick-check", "Быстрая проверка безопасности Linux", ["проверить безопасность linux", "как проверить безопасность в linux", "как проверить безопасность linux", "linux security quick check", "security audit linux", "базовая проверка безопасности linux"], "linux", "Короткая первичная проверка открытых портов, firewall, ошибок входа и привилегий.", ["Это не полноценный аудит, а безопасная стартовая выборка для поиска очевидных рисков.", "Сначала собирайте факты; не отключайте защитные механизмы только ради диагностики."], ["sudo ss -lntup", "sudo ufw status verbose", "sudo firewall-cmd --state", "sudo journalctl -p warning -b", "sudo -l"], ["firewall", "sudo", "ssh", "selinux", "open ports"]),
  card("linux-sudo-basics", "Основы sudo", ["sudo basics", "что такое sudo", "права sudo", "доступ sudo", "как пользоваться sudo", "чтобы не писать sudo"], "linux", "sudo запускает отдельную команду с правами другого пользователя, обычно root, если это разрешено политикой sudoers.", ["Добавление в sudo/wheel обычно не убирает слово sudo из команды.", "NOPASSWD убирает запрос пароля, а не сам sudo, и повышает риск при слишком широких правилах."], ["sudo -l", "sudo COMMAND", "sudo -i"], ["sudoers", "users", "root", "permissions"]),
  card("linux-add-user-sudo", "Добавление пользователя в sudo или wheel", ["как добавить пользователю sudo", "как добавить пользователю права sudo", "как дать пользователю права sudo", "как добавить права пользователю чтобы не писать sudo", "как добавить пользователя права sudo", "как дать права в linux sudo", "как дать sudo пользователю", "как добавить пользователя в группу sudo", "добавить пользователя в группу sudo", "добавить пользователя в sudo group", "usermod -ag sudo", "usermod -ag wheel"], "linux", "Добавляет существующего пользователя в административную группу Debian/Ubuntu `sudo` или RHEL-подобную `wheel`.", ["Используйте -aG: без -a можно случайно удалить пользователя из остальных дополнительных групп.", "После изменения membership нужен новый вход; проверьте правила через sudo -l.", "Точные правила sudoers меняйте через visudo."], ["sudo usermod -aG sudo USER", "sudo usermod -aG wheel USER", "groups USER", "id USER", "sudo visudo"], ["sudo", "sudoers", "wheel", "users", "groups"]),
  card("linux-sudoers-basics", "Безопасное редактирование sudoers", ["sudoers basics", "добавить пользователя в sudoers", "как добавить пользователя в sudoers", "visudo", "настроить sudoers", "sudoers.d"], "linux", "sudoers определяет, кто и какие команды может выполнять через sudo.", ["Редактируйте правила через visudo: он проверяет синтаксис до сохранения.", "Предпочитайте точные команды и отдельный файл в /etc/sudoers.d вместо широкого ALL или NOPASSWD."], ["sudo visudo", "sudo visudo -c", "sudo visudo -f /etc/sudoers.d/USER"], ["sudo", "permissions", "users", "least privilege"]),
  card("linux-user-groups", "Проверка пользователя и его групп", ["проверить группы пользователя", "в каких группах пользователь", "проверить права пользователя", "id username", "groups username", "whoami groups", "whoami", "команда id пользователь"], "linux", "Показывает UID, основную и дополнительные группы пользователя, которые часто определяют доступ к файлам и sudo.", ["`id USER` удобен для полной сводки, `groups USER` — для списка групп.", "После изменения групп пользователь обычно должен войти заново, чтобы получить новый набор membership."], ["whoami", "id USER", "groups USER", "getent group sudo", "getent group wheel"], ["users", "groups", "sudo", "permissions"]),
  card("linux-ssh-access", "Базовая проверка SSH-доступа", ["ssh access basics", "проверить ssh доступ", "sshd status", "authorized_keys", "permitrootlogin", "настроить ssh доступ linux", "не работает ssh вход"], "linux", "Проверяет состояние sshd, ключи пользователя и ключевые ограничения конфигурации SSH.", ["Каталог ~/.ssh обычно должен иметь режим 700, а authorized_keys — 600.", "PermitRootLogin лучше отключать или ограничивать; перед перезапуском проверяйте конфигурацию через sshd -t."], ["systemctl status sshd", "sudo sshd -t", "ls -ld ~/.ssh ~/.ssh/authorized_keys", "sudo sshd -T | grep -i permitrootlogin"], ["ssh", "authorized_keys", "firewall", "users"]),
  card("linux-tar", "Создание и распаковка tar-архивов", ["tar archive", "команда tar", "создать архив linux", "распаковать tar gz", "tar examples"], "linux", "tar объединяет файлы в архив и часто используется вместе с gzip или xz.", ["-c создает архив, -x распаковывает, -t показывает содержимое.", "Перед распаковкой неизвестного архива полезно посмотреть список файлов."], ["tar -czf backup.tar.gz DIR", "tar -tzf backup.tar.gz", "tar -xzf backup.tar.gz"], ["archive", "gzip", "backup"]),
  card("linux-grep", "Практические примеры grep", ["grep examples", "команда grep", "как найти строку в файле", "поиск текста linux", "grep recursive"], "linux", "grep ищет строки по тексту или регулярному выражению.", ["-i игнорирует регистр, -r ищет рекурсивно, -n показывает номера строк.", "Для логов часто полезны контекстные ключи -A, -B и -C."], ["grep -in \"error\" app.log", "grep -Rin \"listen\" /etc/nginx", "journalctl -u SERVICE | grep -i error"], ["text", "logs", "find"]),
  card("linux-find", "Поиск файлов командой find", ["find command", "команда find", "как найти файл linux", "поиск файлов linux", "find examples"], "linux", "find ищет файлы по имени, типу, размеру, времени и другим признакам.", ["Ограничивайте начальный каталог, чтобы ускорить поиск.", "С -exec сначала проверьте выборку без изменяющей команды."], ["find /etc -type f -name '*.conf'", "find /var/log -type f -mtime -1", "find /tmp -type f -size +100M"], ["files", "grep", "large files"]),
  card("linux-rsync", "Основы rsync", ["rsync basics", "команда rsync", "синхронизация файлов linux", "копировать через rsync", "rsync example"], "linux", "rsync эффективно синхронизирует каталоги локально или через SSH.", ["-a сохраняет основные атрибуты, -v показывает процесс.", "Перед --delete полезно выполнить dry-run."], ["rsync -avh SOURCE/ DEST/", "rsync -avhn --delete SOURCE/ DEST/", "rsync -avh DIR/ user@host:/backup/"], ["backup", "ssh", "files"]),
  card("linux-cron", "Основы cron", ["cron basics", "что такое cron", "планировщик linux", "настроить cron", "cron job"], "linux", "cron запускает команды по расписанию от имени пользователя или системы.", ["Окружение cron минимально, поэтому используйте абсолютные пути.", "Перенаправляйте stdout и stderr в лог для диагностики."], ["systemctl status cron", "systemctl status crond", "journalctl -u cron"], ["crontab", "scheduler", "systemd timer"]),
  card("linux-crontab", "Примеры crontab", ["crontab examples", "crontab -e", "пример crontab", "как добавить задачу cron", "посмотреть cron задачи"], "linux", "crontab хранит пользовательские задания cron в формате минута, час, день, месяц, день недели.", ["Проверьте команду вручную перед добавлением в расписание.", "crontab -l показывает задания текущего пользователя."], ["crontab -l", "crontab -e", "0 2 * * * /usr/local/bin/backup.sh >> /var/log/backup.log 2>&1"], ["cron", "scheduler", "logs"])
];

const dockerCards: KnowledgeCard[] = [
  card("docker-ps-all", "Все Docker-контейнеры: docker ps -a", ["docker ps -a", "all docker containers", "показать остановленные контейнеры", "все контейнеры docker"], "docker", "Показывает и запущенные, и остановленные контейнеры.", ["Столбец STATUS помогает увидеть exit code и время остановки.", "Для диагностики затем используйте docker logs и docker inspect."], ["docker ps -a", "docker ps -a --filter status=exited"], ["docker ps", "container", "troubleshooting"]),
  card("docker-logs-follow", "Логи контейнера в реальном времени: docker logs -f", ["docker logs -f", "follow docker logs", "следить за логами контейнера", "как посмотреть логи контейнера", "логи контейнера онлайн"], "docker", "Подключается к stdout/stderr контейнера и продолжает показывать новые строки.", ["--tail ограничивает начальный объем вывода.", "Ctrl+C прекращает просмотр, но не останавливает контейнер."], ["docker logs -f --tail 100 CONTAINER", "docker logs --since 10m CONTAINER"], ["docker logs", "container", "logs"]),
  card("docker-stats", "Ресурсы контейнеров: docker stats", ["docker stats", "docker container resources", "нагрузка контейнеров", "память cpu docker", "как посмотреть нагрузку docker"], "docker", "Показывает CPU, память, сеть и I/O работающих контейнеров.", ["Используйте --no-stream для одного снимка.", "Лимиты контейнера смотрите отдельно через inspect."], ["docker stats", "docker stats --no-stream", "docker inspect CONTAINER --format '{{json .HostConfig.Resources}}'"], ["container", "cpu", "memory"]),
  card("docker-pull", "Загрузка image: docker pull", ["docker pull", "скачать docker image", "pull docker image", "обновить образ docker"], "docker", "Загружает image или конкретный tag из registry.", ["Без tag обычно используется latest, но это не гарантия самой новой версии.", "Для воспроизводимости фиксируйте версию или digest."], ["docker pull nginx:1.27", "docker pull IMAGE@sha256:DIGEST"], ["image", "registry", "tag"]),
  card("docker-lifecycle", "Остановка и перезапуск контейнера", ["docker stop start restart", "docker restart", "перезапустить контейнер", "остановить контейнер", "запустить остановленный контейнер"], "docker", "Управляет жизненным циклом уже созданного контейнера.", ["stop посылает сигнал завершения и ждет timeout.", "restart удобен для быстрого перезапуска, но не меняет конфигурацию контейнера."], ["docker stop CONTAINER", "docker start CONTAINER", "docker restart CONTAINER"], ["container", "docker ps", "signals"]),
  card("docker-remove", "Удаление контейнеров и images", ["docker rm rmi", "docker rm", "docker rmi", "удалить контейнер docker", "удалить образ docker"], "docker", "Удаляет остановленные контейнеры и неиспользуемые images.", ["Работающий контейнер сначала остановите.", "Перед массовой очисткой проверьте, какие объекты действительно не используются."], ["docker rm CONTAINER", "docker rmi IMAGE", "docker container prune", "docker image prune"], ["container", "image", "cleanup"]),
  card("docker-volume-list", "Список Docker volumes", ["docker volume ls", "список docker volumes", "list docker volumes", "посмотреть тома docker"], "docker", "Показывает именованные volumes, хранящие постоянные данные контейнеров.", ["Dangling volumes не связаны с контейнерами, но могут содержать нужные данные.", "Не удаляйте volume без проверки владельца и содержимого."], ["docker volume ls", "docker volume ls -f dangling=true"], ["volume", "storage", "docker inspect"]),
  card("docker-volume-inspect", "Проверка Docker volume", ["docker volume inspect", "inspect docker volume", "где хранится docker volume", "проверить том docker"], "docker", "Показывает driver, mountpoint, labels и параметры volume.", ["Mountpoint относится к Docker host.", "Для remote driver детали могут отличаться."], ["docker volume inspect VOLUME", "docker inspect CONTAINER --format '{{json .Mounts}}'"], ["volume", "mount", "storage"]),
  card("docker-network-list", "Список Docker networks", ["docker network ls", "список docker networks", "list docker networks", "посмотреть сети docker"], "docker", "Показывает сети Docker и используемые network drivers.", ["bridge — типичная локальная сеть одного host.", "Compose обычно создает отдельную сеть проекта."], ["docker network ls", "docker network ls --filter driver=bridge"], ["network", "bridge", "compose"]),
  card("docker-network-inspect", "Проверка Docker network", ["docker network inspect", "inspect docker network", "контейнеры в сети docker", "проверить сеть docker"], "docker", "Показывает subnet, gateway и подключенные к сети контейнеры.", ["Полезно при ошибках DNS и связи между контейнерами.", "Проверьте, что оба контейнера подключены к одной сети."], ["docker network inspect NETWORK", "docker inspect CONTAINER --format '{{json .NetworkSettings.Networks}}'"], ["network", "dns", "container"]),
  card("docker-start-troubleshooting", "Контейнер не запускается: быстрая диагностика", ["container cannot start", "контейнер не стартует", "контейнер не запускается", "docker container exits", "docker контейнер сразу падает"], "docker", "Последовательно проверяет статус, exit code, логи и фактическую конфигурацию контейнера.", ["Exit code 0 может означать, что основной процесс просто завершился.", "Проверьте command, mounts, environment и доступность зависимостей."], ["docker ps -a", "docker logs --tail 200 CONTAINER", "docker inspect CONTAINER --format '{{.State.ExitCode}} {{.State.Error}}'", "docker start -a CONTAINER"], ["container", "logs", "inspect"]),
  card("docker-port-mapping", "Публикация портов Docker", ["docker port mapping", "проброс портов docker", "docker -p", "порт контейнера", "как открыть порт контейнера"], "docker", "Связывает порт Docker host с портом приложения внутри контейнера.", ["Запись HOST_PORT:CONTAINER_PORT публикует TCP по умолчанию.", "Приложение внутри контейнера должно слушать нужный адрес и порт."], ["docker run -p 8080:80 nginx", "docker port CONTAINER", "docker ps --format 'table {{.Names}}\t{{.Ports}}'"], ["port", "container", "nat"]),
  card("dockerfile-instructions", "Dockerfile: RUN, COPY, ADD, CMD и ENTRYPOINT", ["dockerfile run copy add cmd entrypoint", "dockerfile instructions", "разница cmd entrypoint", "copy или add dockerfile", "run в dockerfile"], "docker", "Основные инструкции Dockerfile формируют image и задают процесс контейнера.", ["RUN выполняется при сборке; CMD и ENTRYPOINT — при запуске.", "COPY предпочтительнее ADD, если не нужны специальные возможности ADD."], ["RUN apt-get update && apt-get install -y curl", "COPY . /app", "ENTRYPOINT [\"/app/server\"]", "CMD [\"--help\"]"], ["dockerfile", "image", "build"]),
  card("docker-image-layers", "Слои Docker image", ["что такое слой docker", "из чего состоит docker-образ", "из чего состоит docker образ", "как посмотреть слои docker", "docker image layers", "слои docker image", "как устроены слои docker", "docker history", "docker image history"], "docker", "Docker image состоит из неизменяемых read-only слоев, а запущенный container добавляет поверх них writable layer.", ["Файловые инструкции Dockerfile могут создавать новые слои image.", "Порядок инструкций влияет на cache, скорость повторной сборки и итоговый размер.", "Секреты нельзя безопасно убрать простым удалением в следующем слое."], ["docker image history IMAGE", "docker history IMAGE", "docker inspect IMAGE", "docker system df"], ["image", "dockerfile", "container", "cache", "layer"]),
  card("docker-build-cache", "Кеш сборки Docker", ["docker build cache", "кеш docker build", "image cache", "сборка docker использует старый кеш", "docker no cache"], "docker", "Docker переиспользует неизменившиеся слои, чтобы ускорить сборку.", ["Сначала копируйте редко меняющиеся dependency-файлы.", "--no-cache отключает reuse слоев, но увеличивает время сборки."], ["docker build -t app .", "docker build --no-cache -t app .", "docker builder prune"], ["build", "layers", "dockerfile"])
];

const composeCards: KnowledgeCard[] = [
  card("compose-ps", "Статус Compose-сервисов: docker compose ps", ["docker compose ps", "compose services status", "статус docker compose", "посмотреть контейнеры compose"], "docker", "Показывает контейнеры текущего Compose-проекта, их статус и опубликованные порты.", ["Запускайте в каталоге с compose.yaml или укажите -f.", "Для остановленных сервисов используйте --all."], ["docker compose ps", "docker compose ps --all"], ["compose", "container", "status"]),
  card("compose-logs-follow", "Логи Compose в реальном времени", ["docker compose logs -f", "follow compose logs", "следить за логами compose", "логи compose онлайн"], "docker", "Объединяет и продолжает показывать новые логи сервисов Compose-проекта.", ["Можно указать один сервис, чтобы уменьшить шум.", "--tail ограничивает начальный объем."], ["docker compose logs -f --tail 100", "docker compose logs -f SERVICE"], ["compose", "logs", "service"]),
  card("compose-restart", "Перезапуск Compose-сервиса", ["docker compose restart", "перезапустить compose", "restart compose service", "рестарт сервиса compose"], "docker", "Перезапускает существующие контейнеры Compose без пересоздания конфигурации.", ["Изменения compose.yaml командой restart не применяются.", "Для пересоздания используйте up -d."], ["docker compose restart", "docker compose restart SERVICE", "docker compose up -d SERVICE"], ["compose", "restart", "service"]),
  card("compose-pull", "Обновление Compose images", ["docker compose pull", "compose pull", "скачать образы compose", "обновить images compose"], "docker", "Загружает новые версии images для сервисов Compose.", ["pull сам по себе не пересоздает работающие контейнеры.", "После загрузки обычно выполняют up -d."], ["docker compose pull", "docker compose up -d"], ["compose", "image", "registry"]),
  card("compose-build", "Сборка Compose-сервисов", ["docker compose build", "compose build", "собрать compose", "пересобрать сервис compose"], "docker", "Собирает images сервисов, у которых указан build context.", ["--no-cache отключает кеш, --pull обновляет базовый image.", "После сборки запустите или пересоздайте сервис через up."], ["docker compose build", "docker compose build --pull SERVICE", "docker compose up -d --build"], ["compose", "build", "dockerfile"]),
  card("compose-exec", "Команда внутри Compose-сервиса", ["docker compose exec", "compose exec", "зайти в compose контейнер", "выполнить команду compose"], "docker", "Запускает команду внутри уже работающего контейнера выбранного Compose-сервиса.", ["Указывается имя service из compose.yaml, а не container ID.", "Для интерактивной shell обычно достаточно exec SERVICE sh."], ["docker compose exec SERVICE sh", "docker compose exec SERVICE bash", "docker compose exec SERVICE env"], ["compose", "docker exec", "shell"]),
  card("compose-config", "Проверка итоговой Compose-конфигурации", ["docker compose config", "validate compose file", "проверить compose yaml", "итоговая конфигурация compose"], "docker", "Валидирует compose.yaml и показывает конфигурацию после подстановки переменных и merge.", ["Полезно перед запуском и при неожиданных значениях environment.", "Секретные значения могут попасть в вывод терминала."], ["docker compose config", "docker compose config --services", "docker compose config --profiles"], ["compose", "yaml", "environment"]),
  card("compose-environment", "Переменные окружения Docker Compose", ["compose environment variables", "переменные docker compose", "env file compose", "подстановка переменных compose"], "docker", "Compose подставляет переменные в YAML и передает environment контейнерам.", ["Файл .env для подстановки не равен env_file внутри контейнера.", "Проверяйте результат через docker compose config."], ["docker compose config", "docker compose --env-file .env.prod config", "docker compose exec SERVICE env"], ["compose", "environment", "config"]),
  card("compose-volumes", "Volumes в Docker Compose", ["compose volumes", "docker compose volumes", "тома docker compose", "данные compose"], "docker", "Volumes сохраняют данные сервисов независимо от жизненного цикла контейнера.", ["Named volume создается и управляется Docker.", "down -v удаляет volumes проекта и может уничтожить данные."], ["docker compose config", "docker volume ls", "docker compose down -v"], ["compose", "volume", "storage"]),
  card("compose-networks", "Networks в Docker Compose", ["compose networks", "docker compose networks", "сети docker compose", "связь сервисов compose"], "docker", "Compose подключает сервисы к сетям и дает DNS-имена по именам сервисов.", ["Сервисы в одной сети обращаются друг к другу по service name.", "Опубликованный host port для внутренней связи обычно не нужен."], ["docker compose config", "docker network ls", "docker network inspect PROJECT_default"], ["compose", "network", "dns"])
];

const kubernetesCards: KnowledgeCard[] = [
  card("kubectl-get-pods-all", "Pod во всех namespaces: kubectl get pods -A", ["kubectl get pods -a", "kubectl get pods --all-namespaces", "поды во всех namespaces", "all kubernetes pods"], "kubernetes", "Показывает Pod во всем кластере, а не только в текущем namespace.", ["Добавьте -o wide для node и Pod IP.", "Для поиска проблем удобно фильтровать строки по статусу."], ["kubectl get pods -A", "kubectl get pods -A -o wide"], ["pod", "namespace", "kubectl"]),
  card("kubectl-get-nodes", "Проверка Kubernetes nodes", ["kubectl get nodes", "список нод kubernetes", "check kubernetes nodes", "статус nodes k8s"], "kubernetes", "Показывает готовность, роли и версии узлов кластера.", ["NotReady требует проверки conditions, kubelet и сети node.", "-o wide показывает внутренние адреса и runtime."], ["kubectl get nodes", "kubectl get nodes -o wide", "kubectl describe node NODE"], ["node", "kubelet", "cluster"]),
  card("kubectl-logs-follow", "Логи Pod в реальном времени: kubectl logs -f", ["kubectl logs -f", "follow kubernetes logs", "следить за логами pod", "логи пода онлайн"], "kubernetes", "Продолжает читать новые stdout/stderr строки контейнера в Pod.", ["Для Pod с несколькими контейнерами укажите -c.", "При рестарте контейнера используйте --previous для прошлых логов."], ["kubectl logs -f POD", "kubectl logs -f POD -c CONTAINER", "kubectl logs POD --previous"], ["pod", "logs", "container"]),
  card("kubectl-events", "События Kubernetes: kubectl get events", ["kubectl get events", "как посмотреть события kubernetes", "kubernetes events", "события k8s", "cluster events"], "kubernetes", "Показывает события scheduler, kubelet, controllers и других компонентов.", ["Сортировка по времени помогает увидеть свежую причину сбоя.", "События имеют ограниченный срок хранения."], ["kubectl get events -A --sort-by=.metadata.creationTimestamp", "kubectl get events --field-selector involvedObject.name=POD"], ["events", "describe", "troubleshooting"]),
  card("kubectl-top-pods", "Ресурсы Pod: kubectl top pods", ["kubectl top pods", "нагрузка pod", "cpu memory pods", "ресурсы pod kubernetes"], "kubernetes", "Показывает текущее потребление CPU и памяти Pod через Metrics Server.", ["Команда требует работающий Metrics Server.", "Сравнивайте usage с requests и limits."], ["kubectl top pods", "kubectl top pods -A --containers"], ["metrics", "cpu", "memory"]),
  card("kubectl-top-nodes", "Ресурсы nodes: kubectl top nodes", ["kubectl top nodes", "нагрузка нод kubernetes", "node cpu memory k8s", "ресурсы nodes"], "kubernetes", "Показывает CPU и память Kubernetes nodes через Metrics Server.", ["Высокий процент может объяснить pressure и проблемы scheduling.", "Подробные conditions смотрите через describe node."], ["kubectl top nodes", "kubectl describe node NODE"], ["metrics", "node", "capacity"]),
  card("kubectl-current-context", "Текущий kubectl context", ["kubectl config current-context", "current kubectl context", "какой кластер kubectl", "проверить текущий context"], "kubernetes", "Показывает, к какому cluster/user/namespace сейчас обращается kubectl.", ["Проверяйте context перед apply или delete.", "Переключение выполняется через use-context."], ["kubectl config current-context", "kubectl config get-contexts", "kubectl config use-context CONTEXT"], ["context", "kubeconfig", "cluster"]),
  card("kubernetes-crashloopbackoff", "Диагностика CrashLoopBackOff", ["crashloopbackoff", "pod crashloopbackoff", "pod не запускается", "под постоянно перезапускается", "kubernetes container crash loop"], "kubernetes", "CrashLoopBackOff означает, что контейнер запускается, падает и Kubernetes увеличивает паузу перед повтором.", ["Проверьте current и previous logs, exit code, events и probes.", "Частые причины: неверная команда, config, secret, зависимость или liveness probe."], ["kubectl describe pod POD", "kubectl logs POD --previous", "kubectl get pod POD -o jsonpath='{.status.containerStatuses[*].state}'"], ["pod", "logs", "probes"]),
  card("kubernetes-imagepullbackoff", "Диагностика ImagePullBackOff", ["imagepullbackoff", "errimagepull", "pod не скачивает image", "ошибка загрузки образа kubernetes", "image pull error k8s"], "kubernetes", "Kubernetes не может загрузить container image и откладывает повторные попытки.", ["Проверьте имя/tag image, доступ к registry, DNS и imagePullSecrets.", "События Pod обычно содержат точный ответ registry."], ["kubectl describe pod POD", "kubectl get pod POD -o jsonpath='{.spec.containers[*].image}'", "kubectl get secret"], ["pod", "registry", "secret"]),
  card("kubernetes-service-types", "Service types: ClusterIP, NodePort, LoadBalancer", ["clusterip nodeport loadbalancer", "kubernetes service types", "типы service kubernetes", "разница clusterip nodeport loadbalancer"], "kubernetes", "Тип Service определяет способ доступа к группе Pod.", ["ClusterIP доступен внутри cluster; NodePort публикует порт на nodes.", "LoadBalancer просит внешнюю интеграцию создать балансировщик."], ["kubectl get svc", "kubectl describe svc SERVICE"], ["service", "network", "load balancer"]),
  card("kubernetes-configmap", "Основы Kubernetes ConfigMap", ["kubernetes configmap", "configmap basics", "что такое configmap", "конфигурация kubernetes"], "kubernetes", "ConfigMap хранит несекретную конфигурацию отдельно от container image.", ["Данные подключаются как environment или files.", "Изменение ConfigMap не всегда автоматически перезапускает Pod."], ["kubectl get configmap", "kubectl describe configmap NAME", "kubectl create configmap NAME --from-file=config.yaml"], ["configuration", "pod", "secret"]),
  card("kubernetes-secret", "Основы Kubernetes Secret", ["kubernetes secret", "secret basics", "что такое secret kubernetes", "секреты k8s"], "kubernetes", "Secret передает чувствительные значения Pod через environment или volumes.", ["Base64 encoding не является шифрованием.", "Ограничьте RBAC-доступ и настройте encryption at rest при необходимости."], ["kubectl get secrets", "kubectl describe secret NAME", "kubectl create secret generic NAME --from-literal=key=value"], ["security", "configmap", "rbac"]),
  card("kubernetes-probes", "Liveness и readiness probes", ["liveness readiness probes", "kubernetes probes", "liveness probe", "readiness probe", "проверки здоровья pod"], "kubernetes", "Probes определяют, когда контейнер перезапустить и когда Pod готов принимать трафик.", ["Liveness отвечает за рестарт; readiness — за участие в Service endpoints.", "Слишком строгие значения могут вызвать искусственный CrashLoop."], ["kubectl describe pod POD", "kubectl get pod POD -o yaml"], ["healthcheck", "pod", "service"])
];

const networkingCards: KnowledgeCard[] = [
  card("network-tcp-port", "Проверка TCP-порта", ["как проверить доступность порта", "проверить доступность порта", "check tcp port", "проверить tcp порт", "как проверить порт", "проверить порт host", "доступен ли порт"], "networking", "Проверяет, устанавливается ли TCP-соединение с конкретным host и port.", ["Для локального сервиса сначала проверьте, слушает ли процесс порт через ss или netstat.", "Для удаленной доступности проверяйте соединение с той же сети, где находится реальный клиент.", "Открытый TCP port не гарантирует корректный ответ приложения."], ["Test-NetConnection HOST -Port PORT", "nc -vz HOST PORT", "curl -v telnet://HOST:PORT"], ["tcp", "port", "firewall", "ss", "netstat"]),
  card("network-udp", "Основы проверки UDP", ["check udp port", "проверить udp порт", "udp basics", "проверка udp", "nc udp"], "networking", "UDP не устанавливает соединение, поэтому отсутствие ответа не всегда означает закрытый порт.", ["Используйте протокольный запрос, если он известен, например DNS.", "Firewall может молча отбрасывать пакеты."], ["nc -vzu HOST 53", "dig @HOST example.com", "sudo tcpdump -ni any udp port 53"], ["udp", "dns", "firewall"]),
  card("network-dns-troubleshooting", "Диагностика DNS", ["dns troubleshooting", "dns не работает", "проблемы dns", "не разрешается имя", "ошибка name resolution"], "networking", "Разделяет проблемы resolver, DNS-сервера, записи и сетевой доступности.", ["Сравните запрос к системному resolver и известному DNS-серверу.", "Проверьте suffix, search domains, кеш и правильность record type."], ["nslookup example.com", "nslookup example.com 8.8.8.8", "dig example.com +trace", "ipconfig /flushdns"], ["dns", "nslookup", "dig"]),
  card("network-default-gateway", "Проверка default gateway", ["default gateway", "шлюз по умолчанию", "проверить gateway", "какой шлюз linux windows"], "networking", "Default gateway получает трафик к сетям, для которых нет более точного маршрута.", ["Сначала проверьте локальный адрес и route table.", "Недоступный gateway ломает выход за пределы локальной subnet."], ["ip route | grep default", "route print", "ipconfig /all"], ["routing", "subnet", "ip address"]),
  card("network-cidr", "Subnet mask и CIDR", ["subnet mask cidr", "маска подсети", "что такое cidr", "рассчитать подсеть", "24 subnet"], "networking", "CIDR-префикс определяет сетевую и host-часть IP-адреса.", ["/24 соответствует маске 255.255.255.0.", "Устройства считают адрес локальным, если он попадает в их subnet."], ["ipcalc 192.168.1.10/24", "Get-NetIPAddress"], ["subnet", "routing", "gateway"]),
  card("network-arp", "Проверка ARP-таблицы", ["arp table", "таблица arp", "проверить arp", "ip neigh", "mac адрес по ip"], "networking", "ARP/neighbor table связывает IPv4-адреса локальной сети с MAC-адресами.", ["FAILED или INCOMPLETE указывает на отсутствие L2-ответа.", "Записи динамические и могут устаревать."], ["ip neigh show", "arp -a", "Get-NetNeighbor"], ["layer 2", "mac", "gateway"]),
  card("network-route-troubleshooting", "Диагностика маршрутизации", ["route troubleshooting", "не работает маршрут", "проверить маршрутизацию", "куда идет трафик", "route problem"], "networking", "Проверяет выбранный маршрут, gateway и путь пакетов до назначения.", ["Самый специфичный route имеет приоритет.", "Сравните route table, traceroute и правила firewall/NAT."], ["ip route get 8.8.8.8", "ip route", "traceroute 8.8.8.8", "route print"], ["routing", "gateway", "traceroute"])
];

const windowsCards: KnowledgeCard[] = [
  card("windows-whoami-groups", "Группы текущего пользователя: whoami /groups", ["whoami /groups", "группы пользователя windows", "user group membership windows", "в каких группах пользователь"], "active-directory", "Показывает группы и SID, включенные в текущий Windows access token.", ["После изменения membership может потребоваться новый вход.", "Deny-only и disabled SID важны при анализе реальных прав."], ["whoami /groups", "whoami /all"], ["ad groups", "token", "permissions"]),
  card("windows-flush-dns", "Очистка DNS-кеша Windows", ["ipconfig /flushdns", "flush dns cache", "очистить dns кеш", "сбросить dns windows"], "active-directory", "Удаляет локально закешированные DNS-ответы клиента Windows.", ["Полезно после изменения записи или исправления resolver.", "Команда не исправляет неправильную запись на DNS-сервере."], ["ipconfig /displaydns", "ipconfig /flushdns", "Resolve-DnsName HOST"], ["dns", "cache", "windows"]),
  card("windows-secure-channel", "Проверка secure channel компьютера", ["test-computersecurechannel", "check secure channel", "проверить secure channel", "сломано доверие домена", "trust relationship failed"], "active-directory", "Проверяет доверительный канал между domain member и Active Directory domain.", ["False указывает на проблему machine account, DNS, времени или связи с DC.", "Ремонт выполняйте только после проверки DNS и доступности контроллера."], ["Test-ComputerSecureChannel -Verbose", "Test-ComputerSecureChannel -Repair -Credential DOMAIN\\Admin", "nltest /sc_verify:DOMAIN"], ["domain", "computer account", "domain controller"]),
  card("ad-groups", "Группы Active Directory", ["ad groups", "группы active directory", "проверить группы ad", "get-adgroup", "group membership ad"], "active-directory", "AD groups объединяют пользователей, компьютеры и другие группы для назначения доступа.", ["Security groups используются в ACL, distribution groups — для почты.", "Scope Domain Local, Global и Universal влияет на допустимое membership и область использования."], ["Get-ADGroup -Filter *", "Get-ADPrincipalGroupMembership USER", "Get-ADGroupMember GROUP"], ["permissions", "users", "nested groups"]),
  card("ad-user-lookup", "Поиск пользователя Active Directory", ["как проверить пользователя ad", "проверить пользователя ad", "как найти пользователя active directory", "найти пользователя active directory", "get-aduser identity", "get-aduser filter"], "active-directory", "Находит учетную запись пользователя в Active Directory и показывает ее основные свойства.", ["Для точного login используйте -Identity.", "Для поиска по имени применяйте -Filter; в графическом ADUC можно использовать поиск по домену или OU."], ["Get-ADUser -Identity username", "Get-ADUser -Filter 'Name -like \"*Ivan*\"'"], ["active directory", "users", "aduc", "powershell"]),
  card("ad-nested-groups", "Вложенные группы Active Directory", ["nested groups", "вложенные группы ad", "группа в группе active directory", "recursive group membership"], "active-directory", "Вложенные группы упрощают модель ролей, но могут скрывать источник эффективного доступа.", ["Для рекурсивного membership используйте специальный LDAP matching rule или PowerShell.", "Изменения token membership требуют нового входа пользователя."], ["Get-ADGroupMember GROUP -Recursive", "Get-ADPrincipalGroupMembership USER"], ["ad groups", "permissions", "token"]),
  card("ad-sysvol", "Основы SYSVOL", ["sysvol basics", "что такое sysvol", "sysvol active directory", "проверить sysvol"], "active-directory", "SYSVOL хранит общие части GPO и logon scripts, реплицируемые между Domain Controllers.", ["Каталог публикуется через сетевые shares SYSVOL и NETLOGON.", "Проблемы DFSR могут приводить к разным версиям GPO на DC."], ["net share", "dcdiag /test:sysvolcheck", "dfsrdiag ReplicationState"], ["gpo", "dfsr", "domain controller"]),
  card("windows-dns-role", "Основы DNS Server в Windows", ["windows dns role", "dns role basics", "роль dns windows server", "проверить dns server windows"], "active-directory", "Windows DNS Server обслуживает zones и часто хранит AD-integrated зоны домена.", ["Проверьте состояние службы DNS, зоны и forwarders.", "Для AD критичны SRV-записи и использование внутреннего DNS клиентами."], ["Get-Service DNS", "Get-DnsServerZone", "Get-DnsServerForwarder", "dcdiag /test:dns"], ["dns", "active directory", "srv records"]),
  card("windows-event-viewer", "Основы Event Viewer", ["event viewer basics", "просмотр событий windows", "логи windows", "как посмотреть события windows", "get-winevent"], "active-directory", "Event Viewer хранит системные, security и application события Windows.", ["Фильтруйте по времени, level, source и Event ID.", "Для автоматизации используйте Get-WinEvent."], ["eventvwr.msc", "Get-WinEvent -LogName System -MaxEvents 50", "Get-WinEvent -FilterHashtable @{LogName='System'; Level=2}"], ["windows", "logs", "event id"]),
  card("windows-service-status", "Статус Windows service", ["windows service status", "проверить службу windows", "get-service", "powershell get-service", "статус сервиса windows"], "active-directory", "Показывает состояние Windows services и тип запуска.", ["Get-Service удобен для статуса, Get-CimInstance дает дополнительные свойства.", "Проверьте зависимые службы и Event Viewer при ошибке запуска."], ["Get-Service -Name SERVICE", "sc.exe query SERVICE", "Get-CimInstance Win32_Service -Filter \"Name='SERVICE'\""], ["windows service", "powershell", "event viewer"]),
  card("windows-service-restart", "Перезапуск Windows service", ["restart windows service", "перезапустить службу windows", "restart-service", "powershell restart-service"], "active-directory", "Останавливает и повторно запускает выбранную Windows service.", ["Команда требует соответствующих прав.", "При зависании stop проверьте PID и причину в Event Viewer."], ["Restart-Service -Name SERVICE", "Restart-Service -Name SERVICE -Force", "sc.exe stop SERVICE && sc.exe start SERVICE"], ["windows service", "powershell", "status"]),
  card("windows-test-netconnection", "Проверка сети: Test-NetConnection", ["test-netconnection", "powershell test-netconnection", "проверить порт powershell", "test tcp port windows"], "active-directory", "PowerShell-команда проверяет DNS, ICMP, route и TCP port в Windows.", ["TcpTestSucceeded — ключевой результат проверки порта.", "-DiagnoseRouting помогает увидеть выбранный route и source address."], ["Test-NetConnection HOST -Port 443", "Test-NetConnection HOST -TraceRoute", "Test-NetConnection HOST -DiagnoseRouting"], ["tcp", "port", "powershell"])
];

const proxmoxCards: KnowledgeCard[] = [
  card("proxmox-version", "Версия Proxmox VE: pveversion", ["pveversion", "версия proxmox", "check proxmox version", "пакеты pve"], "proxmox", "Показывает версию Proxmox VE и установленных компонентов.", ["-v выводит версии основных PVE-пакетов.", "Полезно перед обновлением и при сравнении nodes cluster."], ["pveversion", "pveversion -v"], ["proxmox", "packages", "update"]),
  card("proxmox-storage-status", "Статус хранилищ Proxmox: pvesm status", ["pvesm status", "как посмотреть хранилища proxmox", "proxmox storage status", "проверить storage proxmox"], "proxmox", "Показывает доступность, тип, емкость и заполнение настроенных Proxmox storages.", ["Inactive storage может блокировать запуск VM, backup и migration.", "Проверяйте также mount, сеть и конфигурацию storage."], ["pvesm status", "pvesm list STORAGE", "cat /etc/pve/storage.cfg"], ["storage", "backup", "cluster"]),
  card("proxmox-qm-list", "Список виртуальных машин Proxmox", ["qm list", "список vm proxmox", "list proxmox vms", "виртуальные машины proxmox"], "proxmox", "Показывает QEMU/KVM virtual machines, VMID, имя, статус и память.", ["Для деталей конкретной VM используйте qm status и qm config.", "VMID уникален в cluster."], ["qm list", "qm status VMID", "qm config VMID"], ["vm", "qemu", "proxmox"]),
  card("proxmox-qm-status", "Статус VM Proxmox", ["qm status", "статус vm proxmox", "check proxmox vm status", "qm config"], "proxmox", "Проверяет состояние и конфигурацию конкретной QEMU virtual machine.", ["status показывает running/stopped.", "config помогает проверить disks, network и boot settings."], ["qm status VMID", "qm config VMID"], ["vm", "qemu", "troubleshooting"]),
  card("proxmox-qm-lifecycle", "Запуск и остановка VM Proxmox", ["qm start stop", "qm start", "qm stop", "запустить vm proxmox", "остановить vm proxmox"], "proxmox", "Управляет жизненным циклом QEMU virtual machine по VMID.", ["shutdown запрашивает корректное завершение через guest OS.", "stop — жесткая остановка, используйте ее осторожно."], ["qm start VMID", "qm shutdown VMID", "qm stop VMID", "qm reboot VMID"], ["vm", "qemu", "lifecycle"]),
  card("proxmox-pct-list", "Список LXC-контейнеров Proxmox", ["pct list", "список lxc proxmox", "proxmox containers list", "контейнеры proxmox"], "proxmox", "Показывает LXC containers, CTID, статус и имя.", ["Для деталей используйте pct status и pct config.", "LXC отличается от Docker-контейнеров и использует системную виртуализацию."], ["pct list", "pct status CTID", "pct config CTID"], ["lxc", "container", "proxmox"]),
  card("proxmox-pct-status", "Статус LXC-контейнера Proxmox", ["pct status", "статус lxc proxmox", "check proxmox container", "pct start stop"], "proxmox", "Проверяет и управляет состоянием LXC container.", ["pct enter открывает shell работающего контейнера.", "При ошибке запуска смотрите task log и system journal node."], ["pct status CTID", "pct start CTID", "pct shutdown CTID", "pct enter CTID"], ["lxc", "container", "logs"]),
  card("proxmox-vzdump", "Резервное копирование Proxmox: vzdump", ["vzdump basics", "vzdump", "backup proxmox vm", "резервная копия proxmox"], "proxmox", "Создает backup VM или LXC container на выбранном storage.", ["Mode snapshot уменьшает downtime при поддерживаемом storage.", "Всегда проверяйте свободное место и восстановление backup."], ["vzdump VMID --storage STORAGE --mode snapshot", "pvesm list STORAGE --content backup"], ["backup", "storage", "restore"]),
  card("proxmox-cluster-status", "Статус Proxmox cluster", ["pvecm status", "check proxmox cluster status", "статус кластера proxmox", "proxmox quorum"], "proxmox", "Показывает membership, quorum и состояние Corosync cluster.", ["Без quorum часть операций cluster блокируется для защиты конфигурации.", "Проверяйте связь nodes и Corosync links."], ["pvecm status", "pvecm nodes", "journalctl -u corosync -b"], ["cluster", "quorum", "corosync"]),
  card("proxmox-node-resources", "Ресурсы Proxmox node", ["check proxmox node resources", "proxmox node resources", "нагрузка proxmox", "ресурсы ноды proxmox", "cpu memory proxmox"], "proxmox", "Проверяет CPU, память, load, disks и активные guests на Proxmox node.", ["Сопоставляйте host usage с VM/CT consumption.", "Для storage latency дополнительно смотрите iostat."], ["pvesh get /nodes/$(hostname)/status", "top", "free -h", "df -h", "iostat -xz 1"], ["node", "cpu", "memory", "storage"])
];

const gitCards: KnowledgeCard[] = [
  card("git-status", "Состояние репозитория: git status", ["git status", "статус git", "что изменено git", "check git working tree"], "git", "Показывает branch, staged, unstaged и untracked files.", ["Начинайте диагностику Git почти всегда с этой команды.", "-sb дает компактный вывод."], ["git status", "git status -sb"], ["working tree", "staging", "branch"]),
  card("git-add", "Добавление изменений: git add", ["git add", "добавить файлы git", "stage changes git", "git staging"], "git", "Добавляет выбранные изменения в staging area для следующего commit.", ["git add -p позволяет выбрать отдельные hunks.", "Перед commit проверьте staged diff."], ["git add FILE", "git add -p", "git diff --cached"], ["staging", "commit", "diff"]),
  card("git-commit", "Создание commit: git commit", ["git commit", "создать коммит", "commit changes git", "git commit message"], "git", "Сохраняет staged snapshot в локальной истории Git.", ["Commit должен быть небольшим и логически цельным.", "Проверьте staged diff и напишите понятное сообщение."], ["git diff --cached", "git commit -m \"Describe the change\""], ["staging", "history", "message"]),
  card("git-push", "Отправка commits: git push", ["git push", "отправить изменения git", "push branch", "запушить ветку"], "git", "Отправляет локальные commits и refs в remote repository.", ["Для новой branch задайте upstream через -u.", "Отклоненный push обычно требует сначала получить remote changes."], ["git push", "git push -u origin BRANCH"], ["remote", "branch", "pull"]),
  card("git-pull", "Получение изменений: git pull", ["git pull", "получить изменения git", "pull changes", "обновить ветку git"], "git", "Получает remote commits и интегрирует их в текущую branch.", ["pull обычно выполняет fetch плюс merge или rebase.", "Перед операцией проверьте незакоммиченные изменения."], ["git pull --ff-only", "git pull --rebase"], ["fetch", "merge", "rebase"]),
  card("git-checkout", "Переключение Git branch", ["git checkout", "git switch", "переключить ветку git", "checkout branch"], "git", "Переключает working tree на другую branch или восстанавливает выбранные files.", ["Для branch современная команда git switch яснее.", "Не переключайтесь с конфликтующими незакоммиченными изменениями."], ["git switch BRANCH", "git switch -c NEW_BRANCH", "git checkout BRANCH"], ["branch", "working tree", "switch"]),
  card("git-branch", "Работа с Git branches", ["как посмотреть ветки git", "показать все ветки git", "git branch", "список веток git", "создать ветку git", "list git branches"], "git", "Показывает, создает и удаляет локальные branches.", ["Без ключей видны локальные branches, -r показывает remote-tracking branches, -a — все.", "Удаляйте branch только после проверки, что работа сохранена."], ["git branch", "git branch -a", "git branch -r", "git branch NEW_BRANCH", "git branch -d BRANCH"], ["checkout", "remote", "merge"]),
  card("git-log", "История commits: git log", ["git log", "история git", "посмотреть коммиты", "git history"], "git", "Показывает commit history, авторов, даты и связи между branches.", ["--oneline удобен для краткого просмотра.", "--graph помогает увидеть merge history."], ["git log --oneline --decorate -20", "git log --graph --oneline --all", "git show COMMIT"], ["commit", "history", "branch"]),
  card("git-diff", "Просмотр изменений: git diff", ["git diff", "разница git", "посмотреть изменения git", "compare git changes"], "git", "Показывает отличия working tree, staging area или commits.", ["Без аргументов показывает unstaged changes.", "--cached показывает то, что попадет в следующий commit."], ["git diff", "git diff --cached", "git diff BRANCH_A...BRANCH_B"], ["changes", "staging", "commit"]),
  card("git-uncommitted-changes", "Что делать с незакоммиченными изменениями", ["fix uncommitted changes", "незакоммиченные изменения git", "cannot switch branch local changes", "сохранить изменения перед checkout"], "git", "Перед переключением или обновлением решите: commit, временно stash или осознанно отменить изменения.", ["Сначала изучите git status и diff.", "Не используйте destructive reset, пока не уверены, что изменения не нужны."], ["git status", "git diff", "git stash push -u -m \"work in progress\"", "git stash pop"], ["working tree", "stash", "checkout"]),
  card("git-undo-last-commit", "Отмена последнего Git commit", ["как отменить последний commit", "как отменить последний коммит", "как откатить последний commit", "как откатить последний коммит", "undo last commit", "revert last commit"], "git", "Отменяет последний commit с выбором, сохранить ли изменения локально или создать обратный commit.", ["reset --soft снимает commit, но оставляет изменения staged; reset --mixed оставляет их unstaged.", "Для уже опубликованной общей истории безопаснее git revert HEAD, который создает новый обратный commit.", "Не переписывайте shared/pushed history без согласования с командой."], ["git reset --soft HEAD~1", "git reset --mixed HEAD~1", "git revert HEAD"], ["commit", "reset", "revert", "history"]),
  card("git-pull-request", "Pull request", ["что такое pull request", "что такое пул реквест", "pull request", "пул реквест", "merge request"], "git", "Pull request — предложение влить изменения из одной branch в целевую branch.", ["Он объединяет review кода, обсуждение и результаты CI checks перед merge.", "Pull request относится к совместной работе на Git hosting и не является командой git pull."], ["git push -u origin FEATURE_BRANCH"], ["branch", "review", "merge", "ci", "collaboration"])
];

export const expandedKnowledgeCards: KnowledgeCard[] = [
  ...linuxCards,
  ...dockerCards,
  ...composeCards,
  ...kubernetesCards,
  ...networkingCards,
  ...windowsCards,
  ...proxmoxCards,
  ...gitCards
];

function card(
  id: string,
  title: string,
  aliases: string[],
  category: KnowledgeCard["category"],
  shortExplanation: string,
  bullets: string[],
  commands: string[],
  relatedTerms: string[]
): KnowledgeCard {
  return { id, title, aliases, category, shortExplanation, bullets, commands, relatedTerms };
}
